In [3]:
import sys, os
repo_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
if repo_root not in sys.path:
    sys.path.insert(0, repo_root)
print("Added to sys.path:", repo_root)
from fixedincomelib import *
print("Fixed Income Library is loaded.")

Added to sys.path: /Users/nirvana/Documents/QuantBricker
Fixed Income Library is loaded.

## Test Index Regitsry

In [4]:
### index registry basic operations
display(qfListAllIndex())
qfClearIndexRegistry("USD-LIBOR-BBA-1M")
display(qfListAllIndex())
qfClearIndexRegistry()
qfReloadIndexRegistry()
display(qfListAllIndex())

          Type                 Indices
0   IBOR INDEX        USD-LIBOR-BBA-1M
1   IBOR INDEX        USD-LIBOR-BBA-3M
2   IBOR INDEX        USD-LIBOR-BBA-6M
3   IBOR INDEX        USD-LIBOR-BBA-1Y
4   IBOR INDEX  USD-TERM-SOFR-PROXY-1M
..         ...                     ...
82    FX INDEX                 GBP-USD
83    FX INDEX                 EUR-USD
84    FX INDEX                 AUD-USD
85    FX INDEX                 USD-CAD
86    FX INDEX                 USD-JPY

[87 rows x 2 columns]

          Type                 Indices
0   IBOR INDEX        USD-LIBOR-BBA-3M
1   IBOR INDEX        USD-LIBOR-BBA-6M
2   IBOR INDEX        USD-LIBOR-BBA-1Y
3   IBOR INDEX  USD-TERM-SOFR-PROXY-1M
4   IBOR INDEX  USD-TERM-SOFR-PROXY-3M
..         ...                     ...
81    FX INDEX                 GBP-USD
82    FX INDEX                 EUR-USD
83    FX INDEX                 AUD-USD
84    FX INDEX                 USD-CAD
85    FX INDEX                 USD-JPY

[86 rows x 2 columns]

All indices are reloaded from file.

          Type                 Indices
0   IBOR INDEX        USD-LIBOR-BBA-1M
1   IBOR INDEX        USD-LIBOR-BBA-3M
2   IBOR INDEX        USD-LIBOR-BBA-6M
3   IBOR INDEX        USD-LIBOR-BBA-1Y
4   IBOR INDEX  USD-TERM-SOFR-PROXY-1M
..         ...                     ...
82    FX INDEX                 GBP-USD
83    FX INDEX                 EUR-USD
84    FX INDEX                 AUD-USD
85    FX INDEX                 USD-CAD
86    FX INDEX                 USD-JPY

[87 rows x 2 columns]

In [5]:
### register a specific index
index_name = "USD-TERM-SOFR-PROXY-1W"
content = {
    "type": "IBOR INDEX",
    "term": "1W",
    "convention": {
        "currency": "USD",
        "settlement offset": "2D",
        "settlement holidays": "USGS",
        "accrual basis": "Actual/360",
        "payment businessday convention": "F",
        "payment holiday convention": "USGS",
        "end of month": True
    }
}
qfRegisterIndex(index_name, content)
qfDisplayIndex(index_name)

USD-TERM-SOFR-PROXY-1W is registered.

                              Name                   Value
0                       Index Name  USD-TERM-SOFR-PROXY-1W
1                             Type              IBOR INDEX
2                             TERM                      1W
3                         CURRENCY                     USD
4                SETTLEMENT OFFSET                      2D
5              SETTLEMENT HOLIDAYS                    USGS
6                    ACCRUAL BASIS              Actual/360
7   PAYMENT BUSINESSDAY CONVENTION                       F
8       PAYMENT HOLIDAY CONVENTION                    USGS
9                     END OF MONTH                    True
10                  FIXING FUNCTOR                NOT_USED

In [6]:
### pick one representative per index type
# ibor index
display(qfDisplayIndex("USD-LIBOR-BBA-3M"))
# overnight index
display(qfDisplayIndex("SOFR-1B"))
display(qfDisplayIndex("USD-Term SOFR Base-1B"))
# composite index
display(qfDisplayIndex("USD-SOFR-COMPOUND"))
# fx
display(qfDisplayIndex("GBP-USD"))

                              Name               Value
0                       Index Name    USD-LIBOR-BBA-3M
1                             Type          IBOR INDEX
2                             TERM                  3M
3                         CURRENCY                 USD
4                   FIXING FUNCTOR  FIXINGDATE_FUNCTOR
5                    ACCRUAL BASIS          Actual/360
6   PAYMENT BUSINESSDAY CONVENTION                  MF
7       PAYMENT HOLIDAY CONVENTION                 LON
8                     END OF MONTH                True
9                SETTLEMENT OFFSET            NOT_USED
10              SETTLEMENT HOLIDAY                 LON

                              Name               Value
0                       Index Name             SOFR-1B
1                             Type     OVERNIGHT INDEX
2                             TERM                  1D
3                         CURRENCY                 USD
4                   FIXING FUNCTOR  FIXINGDATE_FUNCTOR
5                    ACCRUAL BASIS          Actual/360
6   PAYMENT BUSINESSDAY CONVENTION                   F
7       PAYMENT HOLIDAY CONVENTION                NONE
8                     END OF MONTH               False
9                SETTLEMENT OFFSET            NOT USED
10              SETTLEMENT HOLIDAY                NONE

                             Name                  Value
0                      Index Name  USD-TERM SOFR BASE-1B
1                            Type        OVERNIGHT INDEX
2                            TERM                     1D
3                        CURRENCY                    USD
4               SETTLEMENT OFFSET                     0D
5              SETTLEMENT HOLIDAY                   USGS
6                   ACCRUAL BASIS             Actual/360
7  PAYMENT BUSINESSDAY CONVENTION                      F
8      PAYMENT HOLIDAY CONVENTION                   USGS
9                  FIXING FUNCTOR                   NONE

              Name                      Value
0       Index Name          USD-SOFR-COMPOUND
1             Type  OVERNIGHT COMPOSITE INDEX
2            INDEX                    SOFR-1B
3  COMPOUND METHOD                   COMPOUND

                        Name     Value
0                 Index Name   GBP-USD
1                       Type  FX INDEX
2                   BASE_CCY       GBP
3     BASE_BUSINESS_DAY_CONV         F
4              BASE_HOLIDAYS       LON
5         BASE_FIXING_OFFSET        2D
6                 QUOTED_CCY       USD
7   QUOTED_BUSINESS_DAY_CONV         F
8            QUOTED_HOLIDAYS   LON,NYC
9       QUOTED_FIXING_OFFSET        0D
10               PREMIUM_CCY       USD

## Test FundingIdentifier Regitsry

In [7]:
### funding registry basic operations
display(qfListAllFundingIdentifiers())
qfClearFundingIdentifierRegistry("JPY-GOVT-BOND-FUNDING")
display(qfListAllFundingIdentifiers())
qfClearFundingIdentifierRegistry()
qfReloadFundingIdentifierRegistry()
display(qfListAllFundingIdentifiers())

                      FundingIdentifier
0                                   USD
1                                   CAD
2                                   GBP
3                                   EUR
4                                   AUD
5                                   JPY
6                          SOFR-1B-FLAT
7                         SOFR-1B-CALIB
8                      SOFR-CME-1B-FLAT
9                     SOFR-CME-1B-CALIB
10       USD-FEDERAL FUNDS-H.15-1B-FLAT
11      USD-FEDERAL FUNDS-H.15-1B-CALIB
12   USD-FEDERAL FUNDS-H.15-CME-1B-FLAT
13  USD-FEDERAL FUNDS-H.15-CME-1B-CALIB
14                USD-LIBOR-BBA-3M-FLAT
15               USD-LIBOR-BBA-3M-CALIB
16           USD-TERM SOFR BASE-1B-FLAT
17          USD-TERM SOFR BASE-1B-CALIB
18                        CORRA-1B-FLAT
19                       CORRA-1B-CALIB
20                       CAD-BA-3M-FLAT
21                      CAD-BA-3M-CALIB
22                        SONIA-1B-FLAT
23                       SONIA-1B-CALIB
24                GBP-LIBOR-BBA-3M-FLAT
25               GBP-LIBOR-BBA-3M-CALIB
26                GBP-LIBOR-BBA-6M-FLAT
27               GBP-LIBOR-BBA-6M-CALIB
28                        EONIA-1B-FLAT
29                       EONIA-1B-CALIB
30                      EUROSTR-1B-FLAT
31                     EUROSTR-1B-CALIB
32         EUR-EURIBOR-TELERATE-3M-FLAT
33        EUR-EURIBOR-TELERATE-3M-CALIB
34         EUR-EURIBOR-TELERATE-6M-FLAT
35        EUR-EURIBOR-TELERATE-6M-CALIB
36                        AONIA-1B-FLAT
37                       AONIA-1B-CALIB
38                AUD-LIBOR-BBA-3M-FLAT
39               AUD-LIBOR-BBA-3M-CALIB
40                         TONA-1B-FLAT
41                        TONA-1B-CALIB
42                JPY-LIBOR-BBA-3M-FLAT
43               JPY-LIBOR-BBA-3M-CALIB
44                USD-GOVT-BOND-FUNDING
45                CAD-GOVT-BOND-FUNDING
46                GBP-GOVT-BOND-FUNDING
47           EUR-BUND-GOVT-BOND-FUNDING
48            EUR-OAT-GOVT-BOND-FUNDING
49                AUD-GOVT-BOND-FUNDING
50                JPY-GOVT-BOND-FUNDING

                      FundingIdentifier
0                                   USD
1                                   CAD
2                                   GBP
3                                   EUR
4                                   AUD
5                                   JPY
6                          SOFR-1B-FLAT
7                         SOFR-1B-CALIB
8                      SOFR-CME-1B-FLAT
9                     SOFR-CME-1B-CALIB
10       USD-FEDERAL FUNDS-H.15-1B-FLAT
11      USD-FEDERAL FUNDS-H.15-1B-CALIB
12   USD-FEDERAL FUNDS-H.15-CME-1B-FLAT
13  USD-FEDERAL FUNDS-H.15-CME-1B-CALIB
14                USD-LIBOR-BBA-3M-FLAT
15               USD-LIBOR-BBA-3M-CALIB
16           USD-TERM SOFR BASE-1B-FLAT
17          USD-TERM SOFR BASE-1B-CALIB
18                        CORRA-1B-FLAT
19                       CORRA-1B-CALIB
20                       CAD-BA-3M-FLAT
21                      CAD-BA-3M-CALIB
22                        SONIA-1B-FLAT
23                       SONIA-1B-CALIB
24                GBP-LIBOR-BBA-3M-FLAT
25               GBP-LIBOR-BBA-3M-CALIB
26                GBP-LIBOR-BBA-6M-FLAT
27               GBP-LIBOR-BBA-6M-CALIB
28                        EONIA-1B-FLAT
29                       EONIA-1B-CALIB
30                      EUROSTR-1B-FLAT
31                     EUROSTR-1B-CALIB
32         EUR-EURIBOR-TELERATE-3M-FLAT
33        EUR-EURIBOR-TELERATE-3M-CALIB
34         EUR-EURIBOR-TELERATE-6M-FLAT
35        EUR-EURIBOR-TELERATE-6M-CALIB
36                        AONIA-1B-FLAT
37                       AONIA-1B-CALIB
38                AUD-LIBOR-BBA-3M-FLAT
39               AUD-LIBOR-BBA-3M-CALIB
40                         TONA-1B-FLAT
41                        TONA-1B-CALIB
42                JPY-LIBOR-BBA-3M-FLAT
43               JPY-LIBOR-BBA-3M-CALIB
44                USD-GOVT-BOND-FUNDING
45                CAD-GOVT-BOND-FUNDING
46                GBP-GOVT-BOND-FUNDING
47           EUR-BUND-GOVT-BOND-FUNDING
48            EUR-OAT-GOVT-BOND-FUNDING
49                AUD-GOVT-BOND-FUNDING

All funding identifiers are reloaded from file.

                      FundingIdentifier
0                                   USD
1                                   CAD
2                                   GBP
3                                   EUR
4                                   AUD
5                                   JPY
6                          SOFR-1B-FLAT
7                         SOFR-1B-CALIB
8                      SOFR-CME-1B-FLAT
9                     SOFR-CME-1B-CALIB
10       USD-FEDERAL FUNDS-H.15-1B-FLAT
11      USD-FEDERAL FUNDS-H.15-1B-CALIB
12   USD-FEDERAL FUNDS-H.15-CME-1B-FLAT
13  USD-FEDERAL FUNDS-H.15-CME-1B-CALIB
14                USD-LIBOR-BBA-3M-FLAT
15               USD-LIBOR-BBA-3M-CALIB
16           USD-TERM SOFR BASE-1B-FLAT
17          USD-TERM SOFR BASE-1B-CALIB
18                        CORRA-1B-FLAT
19                       CORRA-1B-CALIB
20                       CAD-BA-3M-FLAT
21                      CAD-BA-3M-CALIB
22                        SONIA-1B-FLAT
23                       SONIA-1B-CALIB
24                GBP-LIBOR-BBA-3M-FLAT
25               GBP-LIBOR-BBA-3M-CALIB
26                GBP-LIBOR-BBA-6M-FLAT
27               GBP-LIBOR-BBA-6M-CALIB
28                        EONIA-1B-FLAT
29                       EONIA-1B-CALIB
30                      EUROSTR-1B-FLAT
31                     EUROSTR-1B-CALIB
32         EUR-EURIBOR-TELERATE-3M-FLAT
33        EUR-EURIBOR-TELERATE-3M-CALIB
34         EUR-EURIBOR-TELERATE-6M-FLAT
35        EUR-EURIBOR-TELERATE-6M-CALIB
36                        AONIA-1B-FLAT
37                       AONIA-1B-CALIB
38                AUD-LIBOR-BBA-3M-FLAT
39               AUD-LIBOR-BBA-3M-CALIB
40                         TONA-1B-FLAT
41                        TONA-1B-CALIB
42                JPY-LIBOR-BBA-3M-FLAT
43               JPY-LIBOR-BBA-3M-CALIB
44                USD-GOVT-BOND-FUNDING
45                CAD-GOVT-BOND-FUNDING
46                GBP-GOVT-BOND-FUNDING
47           EUR-BUND-GOVT-BOND-FUNDING
48            EUR-OAT-GOVT-BOND-FUNDING
49                AUD-GOVT-BOND-FUNDING
50                JPY-GOVT-BOND-FUNDING

In [8]:
### register a specific index
fi_name = "JPY-LIBOR-BBA-6M-FLAT"
content = {
    "currency": "JPY",
    "base index": "JPY-LIBOR-BBA-6M"
}
qfRegisterFundingIdentifier(fi_name, content)
qfDisplayFundingIdentifier(fi_name)

JPY-LIBOR-BBA-6M-FLAT is registered.

         Name                  Value
0  Index Name  JPY-LIBOR-BBA-6M-FLAT
1        Type     FUNDING IDENTIFIER
2    CURRENCY                    JPY
3  BASE INDEX       JPY-LIBOR-BBA-6M

In [9]:
### pick one representative per funding type
# currency funding
display(qfDisplayFundingIdentifier("USD"))
# index funding
display(qfDisplayFundingIdentifier("SOFR-1B-FLAT"))
### standalone funding
display(qfDisplayFundingIdentifier("USD-GOVT-BOND-FUNDING"))

         Name               Value
0  Index Name                 USD
1        Type  FUNDING IDENTIFIER
2    CURRENCY                 USD
3  BASE INDEX             SOFR-1B

         Name               Value
0  Index Name        SOFR-1B-FLAT
1        Type  FUNDING IDENTIFIER
2    CURRENCY                 USD
3  BASE INDEX             SOFR-1B

         Name                  Value
0  Index Name  USD-GOVT-BOND-FUNDING
1        Type     FUNDING IDENTIFIER
2    CURRENCY                    USD
3  BASE INDEX

### Fixings Management

In [10]:
### list index fixings
index_name = 'usd-federal funds-h.15-1d'
qfListIndexFixings(index_name)

           Date  Fixing
0    2025-01-01   0.025
1    2025-01-02   0.025
2    2025-01-03   0.025
3    2025-01-04   0.025
4    2025-01-05   0.025
..          ...     ...
352  2025-12-19   0.025
353  2025-12-20   0.025
354  2025-12-21   0.025
355  2025-12-22   0.025
356  2025-12-23   0.025

[357 rows x 2 columns]

In [11]:
### list index fixings for a specific start date and end date
index_name = 'usd-federal funds-h.15-1d'
qfReloadIndexFixings() # load all back for testing below
qfListIndexFixings(
    index_name,
    start_date='2025-06-17',
    end_date='2025-06-18'
)

All fxings are reloaded from file.

         Date  Fixing
0  2025-06-17   0.025
1  2025-06-18   0.025

In [12]:
index_name = 'usd-federal funds-h.15-1d'
### insert index fixings
qfInsertIndexFixing(index_name, '2026-07-08', 0.02736)
display(qfListIndexFixings(index_name))
# insert more
dates = ['2026-07-09', '2026-07-10']
fixings = [0.02, 0.02]
qfInsertIndexFixing(index_name, dates, fixings)
display(qfListIndexFixings(index_name))
# remove index fixings
qfRemoveIndexFixings(index_name, dates)
display(qfListIndexFixings(index_name))

1 fixing(s) for usd-federal funds-h.15-1d is(are) inserted.

           Date   Fixing
0    2025-01-01  0.02500
1    2025-01-02  0.02500
2    2025-01-03  0.02500
3    2025-01-04  0.02500
4    2025-01-05  0.02500
..          ...      ...
353  2025-12-20  0.02500
354  2025-12-21  0.02500
355  2025-12-22  0.02500
356  2025-12-23  0.02500
357  2026-07-08  0.02736

[358 rows x 2 columns]

2 fixing(s) for usd-federal funds-h.15-1d is(are) inserted.

           Date   Fixing
0    2025-01-01  0.02500
1    2025-01-02  0.02500
2    2025-01-03  0.02500
3    2025-01-04  0.02500
4    2025-01-05  0.02500
..          ...      ...
355  2025-12-22  0.02500
356  2025-12-23  0.02500
357  2026-07-08  0.02736
358  2026-07-09  0.02000
359  2026-07-10  0.02000

[360 rows x 2 columns]

2 fixings of usd-federal funds-h.15-1d are moved.

           Date   Fixing
0    2025-01-01  0.02500
1    2025-01-02  0.02500
2    2025-01-03  0.02500
3    2025-01-04  0.02500
4    2025-01-05  0.02500
..          ...      ...
353  2025-12-20  0.02500
354  2025-12-21  0.02500
355  2025-12-22  0.02500
356  2025-12-23  0.02500
357  2026-07-08  0.02736

[358 rows x 2 columns]

In [13]:
### remove all fixings
# remove all index fixings
qfRemoveIndexFixings('*')
qfListAllIndexFixings()

Empty DataFrame
Columns: [Index]
Index: []

In [14]:
qfListAllIndexFixings('*')

Empty DataFrame
Columns: [Index]
Index: []

In [15]:
### remove a specific fixing
index_name = 'USD-Federal Funds-H.15-1D'
qfReloadIndexFixings() # load all back for testing below
qfRemoveIndexFixings(index_name)
qfListAllIndexFixings(index_name)
qfListAllIndexFixings('*')

All fxings are reloaded from file.
The fixings of USD-Federal Funds-H.15-1D are all removed.

      Index
0   SOFR-1D
1  SONIA-1D