In [3]:
import sys, os
repo_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
if repo_root not in sys.path:
    sys.path.insert(0, repo_root)
print("Added to sys.path:", repo_root)
from fixedincomelib import *
print("Fixed Income Library is loaded.")

Added to sys.path: /Users/nirvana/Documents/QuantBricker
Fixed Income Library is loaded.

## Test Data Convention Registry

In [4]:
### index registry basic operations
display(qfListAllDataConventions())
qfClearDataConventionRegistry("USD-LIBOR-BBA-3M-FRN")
display(qfListAllDataConventions())
qfClearDataConventionRegistry()
qfReloadDataConventionRegistry()
display(qfListAllDataConventions)

                                              Name                    Type
0                                 USD-CASH-DEPOSIT            CASH DEPOSIT
1                             USD-LIBOR-BBA-1M-FRA           FRA OR FIXING
2                             USD-LIBOR-BBA-3M-FRA           FRA OR FIXING
3                             USD-LIBOR-BBA-6M-FRA           FRA OR FIXING
4                             USD-LIBOR-BBA-1Y-FRA           FRA OR FIXING
..                                             ...                     ...
186                                        USD-JPY           FX RATE INDEX
187                     USD-SOFR-COMPOUND-SWAPTION                SWAPTION
188                     USD-SOFR-COMPOUND-CAPFLOOR                CAPFLOOR
189                                  USD-SOFR-JUMP                    JUMP
190  USD-SOFR-OIS-OVER-USD-SOFR-CME-OIS-BASIS-SWAP  SWAP SPREAD BASIS SWAP

[191 rows x 2 columns]

                                              Name                    Type
0                                 USD-CASH-DEPOSIT            CASH DEPOSIT
1                             USD-LIBOR-BBA-1M-FRA           FRA OR FIXING
2                             USD-LIBOR-BBA-3M-FRA           FRA OR FIXING
3                             USD-LIBOR-BBA-6M-FRA           FRA OR FIXING
4                             USD-LIBOR-BBA-1Y-FRA           FRA OR FIXING
..                                             ...                     ...
185                                        USD-JPY           FX RATE INDEX
186                     USD-SOFR-COMPOUND-SWAPTION                SWAPTION
187                     USD-SOFR-COMPOUND-CAPFLOOR                CAPFLOOR
188                                  USD-SOFR-JUMP                    JUMP
189  USD-SOFR-OIS-OVER-USD-SOFR-CME-OIS-BASIS-SWAP  SWAP SPREAD BASIS SWAP

[190 rows x 2 columns]

Data convention is reloaded from file.

In [5]:
### register a specific data convention
conv_name = "USD-LIBOR-BBA-6M-FRN"
content = {
    "type": "FLOATING RATE NOTE",
    "convention": {
        "settlement offset": "2D",
        "settlement holiday convention" : "LON",
        "currency": "USD",
        "notional" : 10_000_000,
        "index" : "USD-LIBOR-BBA-6M",
        "payment businessday convention": "MF",
        "payment holiday convention": "NYC,LON"
    }
}
qfRegisterDataConvention(conv_name, content)
qfDisplayDataConvention(conv_name)

USD-LIBOR-BBA-6M-FRN is registered.

                             Name             Value
0               SETTLEMENT OFFSET                2D
1   SETTLEMENT HOLIDAY CONVENTION               LON
2                        CURRENCY               USD
3                        NOTIONAL          10000000
4                           INDEX  USD-LIBOR-BBA-6M
5  PAYMENT BUSINESSDAY CONVENTION                MF
6      PAYMENT HOLIDAY CONVENTION           NYC,LON

### Test Individual Data Convention

In [6]:
df_all_convs = qfListAllDataConventions()
conv_type_list = list(df_all_convs.Type.unique())

In [7]:
### make sure all display works properly
for conv_type in conv_type_list:
    these_convs = df_all_convs[df_all_convs.Type == conv_type].Name.unique().tolist()
    for this_conv in these_convs:    
        this_conv = DataConventionRegistry().get(this_conv)
        # check display issue
        try:
            this_conv.display()
        except:
            raise Exception(f"There is a display issue for {this_conv}.")