In [1]:
import sys, os
repo_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
if repo_root not in sys.path:
    sys.path.insert(0, repo_root)
print("Added to sys.path:", repo_root)
from fixedincomelib import *
print("Fixed Income Library is loaded.")

Added to sys.path: /Users/nirvana/Documents/QuantBricker
Fixed Income Library is loaded.

## Test All Kinds of Date Functions

In [2]:
start_date = '2025-05-25'
term = '3M'
business_day_convention = 'F'
holiday_convention = 'USGS'
end_date = qfAddPeriod(start_date, term, business_day_convention, holiday_convention)

In [3]:
accrual_basis = 'Actual/Actual (ISDA)'
qfAccrued(start_date, end_date, accrual_basis, business_day_convention, holiday_convention)

0.2520547945205479

In [4]:
test_date = '2025-12-21'
qfMoveToBusinessDay(test_date, business_day_convention, holiday_convention)

'2025-12-22'

In [5]:
qfIsBusinessDay(test_date, holiday_convention)

False

In [6]:
test_date = '2026-01-01'
qfIsHoliday(test_date, holiday_convention)

True

In [7]:
test_date = '2025-12-21'
print(qfIsEndOfMonth(test_date, holiday_convention))
test_date = '2025-12-31'
print(qfIsEndOfMonth(test_date, holiday_convention))

False
True

In [8]:
test_date = '2025-01-01'
qfEndOfMonth(test_date, holiday_convention)

'2025-01-31'

In [9]:
start_date = '2025-05-25'
end_date = '2027-08-25'
period = '6M'
business_day_convention = 'F'
holiday_convention = 'USGS'
accrual_basis = 'Actual/360'
end_of_month = False
fix_in_arrear = True
fixing_offset = '1D'
payment_offset = '2D'
pay_business_day_convention = 'F'
pay_holiday_convention = 'USGS'

In [10]:
print("Short stub at the beginning:")
rule = "BACKWARD"
display(qfCreateSchedule(
    start_date,
    end_date,
    period,
    holiday_convention,
    business_day_convention,
    accrual_basis,
    rule,
    end_of_month,
    fix_in_arrear,
    fixing_offset,
    payment_offset,
    pay_business_day_convention,
    pay_holiday_convention))
print("Long stub at the beginning:")
first_regular_date = "2026-02-25"
display(qfCreateSchedule(
    start_date,
    end_date,
    period,
    holiday_convention,
    business_day_convention,
    accrual_basis,
    rule,
    end_of_month,
    fix_in_arrear,
    fixing_offset,
    payment_offset,
    pay_business_day_convention,
    pay_holiday_convention,
    first_regular_date=first_regular_date))
print("Short stub at the end:")
rule = "FORWARD"
next_to_last_date = "2027-05-25"
display(qfCreateSchedule(
    start_date,
    end_date,
    period,
    holiday_convention,
    business_day_convention,
    accrual_basis,
    rule,
    end_of_month,
    fix_in_arrear,
    fixing_offset,
    payment_offset,
    pay_business_day_convention,
    pay_holiday_convention,
    next_to_last_date=next_to_last_date))
print("Long stub at the end:")
rule = "FORWARD"
next_to_last_date = "2026-11-25"
display(qfCreateSchedule(
    start_date,
    end_date,
    period,
    holiday_convention,
    business_day_convention,
    accrual_basis,
    rule,
    end_of_month,
    fix_in_arrear,
    fixing_offset,
    payment_offset,
    pay_business_day_convention,
    pay_holiday_convention,
    next_to_last_date=next_to_last_date))

Short stub at the beginning:

,StartDate,EndDate,FixingDate,PaymentDate,Accrued
0,"May 27th, 2025","August 25th, 2025","August 26th, 2025","August 27th, 2025",0.250000
1,"August 25th, 2025","February 25th, 2026","February 26th, 2026","February 27th, 2026",0.511111
2,"February 25th, 2026","August 25th, 2026","August 26th, 2026","August 27th, 2026",0.502778
3,"August 25th, 2026","February 25th, 2027","February 26th, 2027","March 1st, 2027",0.511111
4,"February 25th, 2027","August 25th, 2027","August 26th, 2027","August 27th, 2027",0.502778

Long stub at the beginning:

,StartDate,EndDate,FixingDate,PaymentDate,Accrued
0,"May 27th, 2025","February 25th, 2026","February 26th, 2026","February 27th, 2026",0.761111
1,"February 25th, 2026","August 25th, 2026","August 26th, 2026","August 27th, 2026",0.502778
2,"August 25th, 2026","February 25th, 2027","February 26th, 2027","March 1st, 2027",0.511111
3,"February 25th, 2027","August 25th, 2027","August 26th, 2027","August 27th, 2027",0.502778

Short stub at the end:

,StartDate,EndDate,FixingDate,PaymentDate,Accrued
0,"May 27th, 2025","November 25th, 2025","November 26th, 2025","November 28th, 2025",0.505556
1,"November 25th, 2025","May 26th, 2026","May 27th, 2026","May 28th, 2026",0.505556
2,"May 26th, 2026","November 25th, 2026","November 27th, 2026","November 30th, 2026",0.508333
3,"November 25th, 2026","May 25th, 2027","May 26th, 2027","May 27th, 2027",0.502778
4,"May 25th, 2027","August 25th, 2027","August 26th, 2027","August 27th, 2027",0.255556

Long stub at the end:

,StartDate,EndDate,FixingDate,PaymentDate,Accrued
0,"May 27th, 2025","November 25th, 2025","November 26th, 2025","November 28th, 2025",0.505556
1,"November 25th, 2025","May 26th, 2026","May 27th, 2026","May 28th, 2026",0.505556
2,"May 26th, 2026","November 25th, 2026","November 27th, 2026","November 30th, 2026",0.508333
3,"November 25th, 2026","August 25th, 2027","August 26th, 2027","August 27th, 2027",0.758333