In [1]:
import sys, os
import pandas as pd
repo_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
if repo_root not in sys.path:
    sys.path.insert(0, repo_root)
print("Added to sys.path:", repo_root)
from fixedincomelib import *
print("Fixed Income Library is loaded.")

Added to sys.path: /Users/nirvana/Documents/QuantBricker
Fixed Income Library is loaded.

## Test Model Build Method

#### 1. YC IBOR Build Method

In [2]:
# create yield curve index build method
build_method_type = "YC_IBOR_ELEMENT"
content = {
    "TARGET" : "USD-LIBOR-BBA-3M",
    "REFERENCE" : "",
    "FRA OR FIXING" : "USD-LIBOR-BBA-3M-FRA",
    "IBOR FUTURE" : "EURODOLLAR",
    "SWAP" : "USD-SWAP-SEMI-BOND"
}
yc_ibor_build_method = qfCreateBuildMethod(build_method_type, content)
display(qfDisplayModelBuildMethod(yc_ibor_build_method))
yc_ibor_build_method.swap
# serialize / de-serialize
path = 'yc_ibor_build_method.pickle'
qfWriteBuildMethodToFile(yc_ibor_build_method, path)
yc_ibor_build_method_ = qfReadBuildMethodFromFile(path)
# check
display(qfDisplayModelBuildMethod(yc_ibor_build_method_))
# house keeping
os.remove(path)

                             Name                 Value
0                          TARGET      USD-LIBOR-BBA-3M
1                       REFERENCE
2      INSTANTANEOUS FORWARD RATE
3           IBOR SPREAD ZERO RATE
4                   FRA OR FIXING  USD-LIBOR-BBA-3M-FRA
5                 GENERIC FORWARD
6          GENERIC FORWARD SPREAD
7                  GENERIC SPREAD
8                     IBOR FUTURE            EURODOLLAR
9                            SWAP    USD-SWAP-SEMI-BOND
10                  COMPOUND SWAP
11             FLOATING RATE NOTE
12            COMPOUND BASIS SWAP
13            CURRENCY BASIS SWAP
14  OVERNIGHT INDEX CURRENCY SWAP
15     OVERNIGHT INDEX BASIS SWAP
16           INTERPOLATION METHOD
17           EXTRAPOLATION METHOD

                             Name                               Value
0                          TARGET                    USD-LIBOR-BBA-3M
1                       REFERENCE
2      INSTANTANEOUS FORWARD RATE
3           IBOR SPREAD ZERO RATE
4                   FRA OR FIXING                USD-LIBOR-BBA-3M-FRA
5                 GENERIC FORWARD
6          GENERIC FORWARD SPREAD
7                  GENERIC SPREAD
8                     IBOR FUTURE                          EURODOLLAR
9                            SWAP                  USD-SWAP-SEMI-BOND
10                  COMPOUND SWAP
11             FLOATING RATE NOTE
12            COMPOUND BASIS SWAP
13            CURRENCY BASIS SWAP
14  OVERNIGHT INDEX CURRENCY SWAP
15     OVERNIGHT INDEX BASIS SWAP
16           INTERPOLATION METHOD  PIECEWISE_CONSTANT_LEFT_CONTINUOUS
17           EXTRAPOLATION METHOD                                FLAT

#### 2. YC OVERNIGHT INDEX Build Method

In [3]:
# create yield curve index build method
build_method_type = "YC_OVERNIGHT_INDEX_ELEMENT"
content = {
    "TARGET" : "SOFR-1B",
    "REFERENCE" : "",
    "FRA OR FIXING" : "SOFR-1B-FRA",
    "OVERNIGHT INDEX FUTURE" : "SOFR-FUTURE-3M",
    "OVERNIGHT INDEX SWAP" : "USD-SOFR-OIS"
}
yc_on_build_method = qfCreateBuildMethod(build_method_type, content)
display(qfDisplayModelBuildMethod(yc_on_build_method))
# serialize / de-serialize
path = 'yc_on_build_method.pickle'
qfWriteBuildMethodToFile(yc_on_build_method, path)
yc_on_build_method_ = qfReadBuildMethodFromFile(path)
# check
display(qfDisplayModelBuildMethod(yc_on_build_method_))
# house keeping
os.remove(path)

                          Name           Value
0                       TARGET         SOFR-1B
1                    REFERENCE
2   INSTANTANEOUS FORWARD RATE
3        IBOR SPREAD ZERO RATE
4                       FIXING
5                          FRA
6              GENERIC FORWARD
7       GENERIC FORWARD SPREAD
8               GENERIC SPREAD
9                 LIBOR FUTURE
10                        SWAP
11      OVERNIGHT INDEX FUTURE  SOFR-FUTURE-3M
12        OVERNIGHT INDEX SWAP    USD-SOFR-OIS
13  OVERNIGHT INDEX FRA SPREAD
14  OVERNIGHT INDEX BASIS SWAP
15              OIS BASIS SWAP
16        INTERPOLATION METHOD
17        EXTRAPOLATION METHOD

                          Name                               Value
0                       TARGET                             SOFR-1B
1                    REFERENCE
2   INSTANTANEOUS FORWARD RATE
3        IBOR SPREAD ZERO RATE
4                       FIXING
5                          FRA
6              GENERIC FORWARD
7       GENERIC FORWARD SPREAD
8               GENERIC SPREAD
9                 LIBOR FUTURE
10                        SWAP
11      OVERNIGHT INDEX FUTURE                      SOFR-FUTURE-3M
12        OVERNIGHT INDEX SWAP                        USD-SOFR-OIS
13  OVERNIGHT INDEX FRA SPREAD
14  OVERNIGHT INDEX BASIS SWAP
15              OIS BASIS SWAP
16        INTERPOLATION METHOD  PIECEWISE_CONSTANT_LEFT_CONTINUOUS
17        EXTRAPOLATION METHOD                                FLAT

#### 3. YC Funding Build Method

In [4]:
# create yield curve index build method
build_method_type = "YC_FUNDING_ELEMENT"
content = {
    "TARGET" : "SOFR-1B-FLAT",
    "REFERENCE" : "SOFR-1B",
    "IBOR SPREAD ZERO RATE" : "SOFR-1B-OVER-SOFR-1B-FLAT-ISZR"
}
yc_funding_build_method = qfCreateBuildMethod(build_method_type, content)
display(qfDisplayModelBuildMethod(yc_funding_build_method))
# serialize / de-serialize
path = 'yc_funding_build_method.pickle'
qfWriteBuildMethodToFile(yc_funding_build_method, path)
yc_funding_build_method_ = qfReadBuildMethodFromFile(path)
# check
display(qfDisplayModelBuildMethod(yc_funding_build_method_))
# house keeping
os.remove(path)

                                   Name                           Value
0                                TARGET                    SOFR-1B-FLAT
1                             REFERENCE                         SOFR-1B
2            INSTANTANEOUS FORWARD RATE
3                 IBOR SPREAD ZERO RATE  SOFR-1B-OVER-SOFR-1B-FLAT-ISZR
4                          CASH DEPOSIT
5                                   FRA
6                       GENERIC FORWARD
7                GENERIC FORWARD SPREAD
8                        GENERIC SPREAD
9                          LIBOR FUTURE
10                                 SWAP
11                   FLOATING RATE NOTE
12                  CURRENCY BASIS SWAP
13        OVERNIGHT INDEX CURRENCY SWAP
14  OVERNIGHT INDEX BASIS CURRENCY SWAP
15                 INTERPOLATION METHOD
16                 EXTRAPOLATION METHOD

                                   Name                               Value
0                                TARGET                        SOFR-1B-FLAT
1                             REFERENCE                             SOFR-1B
2            INSTANTANEOUS FORWARD RATE
3                 IBOR SPREAD ZERO RATE      SOFR-1B-OVER-SOFR-1B-FLAT-ISZR
4                          CASH DEPOSIT
5                                   FRA
6                       GENERIC FORWARD
7                GENERIC FORWARD SPREAD
8                        GENERIC SPREAD
9                          LIBOR FUTURE
10                                 SWAP
11                   FLOATING RATE NOTE
12                  CURRENCY BASIS SWAP
13        OVERNIGHT INDEX CURRENCY SWAP
14  OVERNIGHT INDEX BASIS CURRENCY SWAP
15                 INTERPOLATION METHOD  PIECEWISE_CONSTANT_LEFT_CONTINUOUS
16                 EXTRAPOLATION METHOD                                FLAT

#### 4. YC_FX_RATE

In [5]:
# create yield curve index build method
build_method_type = "YC_FX_RATE"
content = {
    "TARGET" : "GBP-USD",
    "FX RATE INDEX" : "GBP-USD",
    "BUILD CURRENCY CHAIN" : True
}
yc_fx_rate = qfCreateBuildMethod(build_method_type, content)
display(qfDisplayModelBuildMethod(yc_fx_rate))
# serialize / de-serialize
path = 'yc_fx_rate.pickle'
qfWriteBuildMethodToFile(yc_fx_rate, path)
yc_fx_rate_ = qfReadBuildMethodFromFile(path)
# check
display(qfDisplayModelBuildMethod(yc_fx_rate_))
# house keeping
os.remove(path)

                   Name    Value
0                TARGET  GBP-USD
1         FX RATE INDEX  GBP-USD
2  BUILD CURRENCY CHAIN     True

                   Name    Value
0                TARGET  GBP-USD
1         FX RATE INDEX  GBP-USD
2  BUILD CURRENCY CHAIN     True

#### 5. Yield Curve Common

In [6]:
# create yield curve index build method
build_method_type = "YC_COMMON"
content = {
    "TARGET" : "USD",
    "FUNDING PARAMETERS" : "USD-FUNDING-PARAMETERS"
}
yc_common = qfCreateBuildMethod(build_method_type, content)
display(qfDisplayModelBuildMethod(yc_common))
# serialize / de-serialize
path = 'yc_common.pickle'
qfWriteBuildMethodToFile(yc_common, path)
yc_common_ = qfReadBuildMethodFromFile(path)
# check
display(qfDisplayModelBuildMethod(yc_common_))
# house keeping
os.remove(path)

                 Name                   Value
0              TARGET                     USD
1  FUNDING PARAMETERS  USD-FUNDING-PARAMETERS
2       SOLVER METHOD

                 Name                   Value
0              TARGET                     USD
1  FUNDING PARAMETERS  USD-FUNDING-PARAMETERS
2       SOLVER METHOD     ND_ITERATIVE_SOLVER

## Test Build Method Collection APIs

### qfCreateModelBuildMethodCollection

In [7]:
bm_collection = qfCreateModelBuildMethodCollection(
    [yc_ibor_build_method, 
     yc_on_build_method, 
     yc_funding_build_method, 
     yc_fx_rate,
     yc_common])
assert bm_collection.num_build_methods == 5

retrieved_build_method = qfGetBuildMethodFromBuildMethodCollection(
    bm_collection, 'USD-LIBOR-BBA-3M', 'YC_IBOR_ELEMENT')
assert retrieved_build_method.type == "YC_IBOR_ELEMENT"\
      and retrieved_build_method.target == "USD-LIBOR-BBA-3M"

### qfWriteBuildMethodCollectionToFile / qfReadBuildMethodCollectionFromFile

In [8]:
path = 'test_bm_collection.pickle'

result = qfWriteBuildMethodCollectionToFile(bm_collection, path)
assert result == 'DONE'
assert os.path.exists(path)

bm_col_back = qfReadBuildMethodCollectionFromFile(path)
assert bm_col_back.num_build_methods == bm_collection.num_build_methods

os.remove(path)

### qfDisplayModelBuildMethodCollection

In [9]:
df_col = qfDisplayModelBuildMethodCollection(bm_collection)
display(df_col)

                         Name             Value
0             YC_IBOR_ELEMENT  USD-LIBOR-BBA-3M
1  YC_OVERNIGHT_INDEX_ELEMENT           SOFR-1B
2          YC_FUNDING_ELEMENT      SOFR-1B-FLAT
3                  YC_FX_RATE           GBP-USD
4                   YC_COMMON               USD