In [1]:
import sys, os
import numpy as np
import pandas as pd
repo_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
if repo_root not in sys.path:
    sys.path.insert(0, repo_root)
print("Added to sys.path:", repo_root)
from fixedincomelib import *
print("Fixed Income Library is loaded.")

Added to sys.path: /Users/nirvana/Documents/QuantBricker
Fixed Income Library is loaded.

## Test Data 1D

In [2]:
df = pd.DataFrame(index=['3M', '6M', '9M', '1Y'])
df['values'] = [.03] * len(df)
data_type = 'Overnight Index Future'
data_conv = 'SOFR-FUTURE-3M'
data1D = qfCreateData1D(data_type, data_conv, df)
display(qfDisplayDataObject(data1D))
# serialize
path = 'data1d.pickle'
qfWriteDataObjectToFile(data1D, path)
# deserialize
data1D_back = qfReadDataObjectFromFile(path)
# check
qfDisplayDataObject(data1D_back)
# house keeping
os.remove(path)

  axis1  values
0    3M    0.03
1    6M    0.03
2    9M    0.03
3    1Y    0.03

In [3]:
df = pd.DataFrame(index=['3M', '6M', '9M', '1Y'])
df['values'] = [.03] * len(df)
data_type = 'Instantaneous Forward Rate'
data_conv = 'USD-SOFR-OIS-1B-IFR'
data1D_ifr = qfCreateData1D(data_type, data_conv, df)
display(qfDisplayDataObject(data1D_ifr))
# serialize
path = 'data1d.pickle'
qfWriteDataObjectToFile(data1D_ifr, path)
# deserialize
data1D_ifr_back = qfReadDataObjectFromFile(path)
# check
display(qfDisplayDataObject(data1D_ifr_back))
# house keeping
os.remove(path)

  axis1  values
0    3M    0.03
1    6M    0.03
2    9M    0.03
3    1Y    0.03

  axis1  values
0    3M    0.03
1    6M    0.03
2    9M    0.03
3    1Y    0.03

## Test Data 2D

In [4]:
df = pd.DataFrame(
    np.random.rand(4, 3),
    index=['3M', '6M', '9M', '1Y'], 
    columns=['1Y', '5Y', '10Y'])
data_type = 'Swaption Normal Volatility'
data_conv = 'USD-SOFR-COMPOUND-SWAPTION'
data2D = qfCreateData2D(data_type, data_conv, df)
display(qfDisplayDataObject(data2D))
# serialize
path = 'data2d.pickle'
qfWriteDataObjectToFile(data2D, path)
# deserialize
data2D_back = qfReadDataObjectFromFile(path)
# check
display(qfDisplayDataObject(data2D_back))
# house keeping
os.remove(path)

          1Y        5Y       10Y
3M  0.885659  0.693132  0.836248
6M  0.426638  0.416404  0.306969
9M  0.069088  0.275734  0.582748
1Y  0.720801  0.979186  0.508364

          1Y        5Y       10Y
3M  0.885659  0.693132  0.836248
6M  0.426638  0.416404  0.306969
9M  0.069088  0.275734  0.582748
1Y  0.720801  0.979186  0.508364

## Data Table

In [5]:
df = pd.DataFrame(
    [['2025-01-01', '2025-03-01', 0]]
    , columns=['axis1', 'axis2', 'values'])
data_type = 'JUMP'
data_conv = 'USD-SOFR-JUMP'
data_table = qfCreateDataTable(data_type, data_conv, df)
display(qfDisplayDataObject(data_table))
# serialize
path = 'data_table.pickle'
qfWriteDataObjectToFile(data_table, path)
# deserialize
data_table_back = qfReadDataObjectFromFile(path)
# check
display(qfDisplayDataObject(data_table_back))
# house keeping
os.remove(path)

        axis1       axis2  values
0  2025-01-01  2025-03-01       0

        axis1       axis2  values
0  2025-01-01  2025-03-01       0

## Data Generic

In [6]:
df = pd.DataFrame(
    [
        ['Overnight Index Future', 'SOFR-FUTURE-3M', 'SOFR-1B-FLAT']
    ], 
    columns=['DATA TYPE', 'DATA CONVENTION', 'FUNDING IDENTIFIER'])
data_label = 'USD-FUNDING-PARAMETERS'
dg = qfCreateDataGeneric(data_label, df)
display(qfDisplayDataObject(dg))
# serialize
path = 'data_generic.pickle'
qfWriteDataObjectToFile(dg, path)
# deserialize
dg_back = qfReadDataObjectFromFile(path)
# check
display(qfDisplayDataObject(dg_back))
# house keeping
os.remove(path)

                DATA TYPE DATA CONVENTION FUNDING IDENTIFIER
0  Overnight Index Future  SOFR-FUTURE-3M       SOFR-1B-FLAT

                DATA TYPE DATA CONVENTION FUNDING IDENTIFIER
0  Overnight Index Future  SOFR-FUTURE-3M       SOFR-1B-FLAT

## Test Data Collection

In [7]:
### create a data collection
data_list = [data1D, data2D, dg]
data_collection = qfCreateDataCollection(data_list)
display(qfDisplayDataCollection(data_collection))

     Data Shape                   Data Type             Data Convention
0       DATA 1D      Overnight Index Future              SOFR-FUTURE-3M
1       DATA 2D  Swaption Normal Volatility  USD-SOFR-COMPOUND-SWAPTION
2  DATA GENERIC                 DATAGENERIC      USD-FUNDING-PARAMETERS

In [8]:
### serialization / de-serialization
# serialize
path = 'data_collection.pickle'
qfWriteDataObjectToFile(data_collection, path)
# deserialize
data_collection_back = qfReadDataCollectionFromFile(path)
# check
display(qfDisplayDataCollection(data_collection_back))
# house keeping
os.remove(path)

     Data Shape                   Data Type             Data Convention
0       DATA 1D      Overnight Index Future              SOFR-FUTURE-3M
1       DATA 2D  Swaption Normal Volatility  USD-SOFR-COMPOUND-SWAPTION
2  DATA GENERIC                 DATAGENERIC      USD-FUNDING-PARAMETERS

In [9]:
### get data from data collection
data_type = 'Overnight Index Future'
data_conv = 'SOFR-FUTURE-3M'
data = qfGetDataFromDataCollection(data_collection, data_type, data_conv)
qfDisplayDataObject(data)

  axis1  values
0    3M    0.03
1    6M    0.03
2    9M    0.03
3    1Y    0.03

In [10]:
### get data generic from data collection
data_type = 'DATA GENERIC'
data_conv = 'USD-FUNDING-PARAMETERS'
data = qfGetDataFromDataCollection(data_collection, data_type, data_conv)
qfDisplayDataObject(data)

                DATA TYPE DATA CONVENTION FUNDING IDENTIFIER
0  Overnight Index Future  SOFR-FUTURE-3M       SOFR-1B-FLAT