In [1]:
import sys, os
repo_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
if repo_root not in sys.path:
    sys.path.insert(0, repo_root)
print("Added to sys.path:", repo_root)
from fixedincomelib import *
print("Fixed Income Library is loaded.")

Added to sys.path: /Users/nirvana/Documents/QuantBricker
Fixed Income Library is loaded.

### Product Bullet Cashflow

In [2]:
print("Product creation and display:")
termination_date = "2026-05-26"
currency = "USD"
notional = 1e6
long_or_short = "LONG"
payment_date = "2D"
prod_bullet_cashflow_default = qfCreateProductBulletCashflow(
    termination_date,
    currency,
    notional,
    long_or_short)
display(qfDisplayProduct(prod_bullet_cashflow_default))
prod_bullet_cashflow_customized = qfCreateProductBulletCashflow(
    termination_date,
    currency,
    notional,
    long_or_short,
    payment_date)
display(qfDisplayProduct(prod_bullet_cashflow_customized))
print("Product (de-)serialization:")
# serialize
path = 'product_bullet_cashflow.pickle'
qfWriteProductToFile(prod_bullet_cashflow_customized, path)
# deserialize
prod_bullet_cashflow_customized_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_bullet_cashflow_customized_retrieved))
# house keeping
os.remove(path)

Product creation and display:

                     Name                    Value
0            Product Type  PRODUCT_BULLET_CASHFLOW
1                Notional                1000000.0
2                Currency                      USD
3           Long Or Short                     LONG
4        Termination Date               2026-05-26
5  Payment Date Or Offset                       0D

                     Name                    Value
0            Product Type  PRODUCT_BULLET_CASHFLOW
1                Notional                1000000.0
2                Currency                      USD
3           Long Or Short                     LONG
4        Termination Date               2026-05-26
5  Payment Date Or Offset                       2D

Product (de-)serialization:

                     Name                    Value
0            Product Type  PRODUCT_BULLET_CASHFLOW
1                Notional                1000000.0
2                Currency                      USD
3           Long Or Short                     LONG
4        Termination Date               2026-05-26
5  Payment Date Or Offset                       2D

### Product Fixed Accrued

In [3]:
print("Product creation and display:")
effecitve_date = '2026-03-26'
termination_date = '2026-05-26'
pay_or_rec = "receive"
currency = 'USD'
notional = 1e6
coupon = 0.05
accrual_basis = 'Actual/360'
prod_fixed_accrued_default = qfCreateProducFixedAccrued(
    effecitve_date,
    termination_date,
    pay_or_rec,
    currency,
    notional,
    coupon,
    accrual_basis
)
display(qfDisplayProduct(prod_fixed_accrued_default))
term = "3M"
pay_date = "2026-05-29"
business_day_convention = "F"
holiday_convention = "USGS"
pay_business_day_convention = "F"
pay_holiday_convention = "USGS"
prod_fixed_accrued_customized = qfCreateProducFixedAccrued(
    effecitve_date,
    termination_date,
    pay_or_rec,
    currency,
    notional,
    coupon,
    accrual_basis,
    business_day_convention,
    holiday_convention,
    pay_date,
    pay_business_day_convention,
    pay_holiday_convention)
display(qfDisplayProduct(prod_fixed_accrued_customized))
prod_fixed_accrued_customized_term = qfCreateProducFixedAccrued(
    effecitve_date,
    termination_date,
    pay_or_rec,
    currency,
    notional,
    coupon,
    accrual_basis,
    business_day_convention,
    holiday_convention,
    "3M",
    pay_business_day_convention,
    pay_holiday_convention)
display(qfDisplayProduct(prod_fixed_accrued_customized_term))
print("Product (de-)serialization:")
# serialize
path = 'product_fixed_accured_cashflow.pickle'
qfWriteProductToFile(prod_fixed_accrued_customized_term, path)
# deserialize
prod_fixed_accrued_customized_term_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_fixed_accrued_customized_term_retrieved))
# house keeping
os.remove(path)

Product creation and display:

                               Name                  Value
0                      Product Type  PRODUCT_FIXED_ACCRUED
1                          Notional              1000000.0
2                          Currency                    USD
3                     Long Or Short                   LONG
4                    Effective Date             2026-03-26
5          Term Or Termination Date             2026-05-26
6                    Pay Or Receive                RECEIVE
7                     Accrual Basis             Actual/360
8                            Coupon                   0.05
9           Business Day Convention                   NONE
10               Holiday Convention                   NONE
11           Payment Date Or Offset                     0D
12  Payment Business Day Convention                   NONE
13       Payment Holiday Convention                   NONE

                               Name                  Value
0                      Product Type  PRODUCT_FIXED_ACCRUED
1                          Notional              1000000.0
2                          Currency                    USD
3                     Long Or Short                   LONG
4                    Effective Date             2026-03-26
5          Term Or Termination Date             2026-05-26
6                    Pay Or Receive                RECEIVE
7                     Accrual Basis             Actual/360
8                            Coupon                   0.05
9           Business Day Convention                      F
10               Holiday Convention                   USGS
11           Payment Date Or Offset             2026-05-29
12  Payment Business Day Convention                      F
13       Payment Holiday Convention                   USGS

                               Name                  Value
0                      Product Type  PRODUCT_FIXED_ACCRUED
1                          Notional              1000000.0
2                          Currency                    USD
3                     Long Or Short                   LONG
4                    Effective Date             2026-03-26
5          Term Or Termination Date             2026-05-26
6                    Pay Or Receive                RECEIVE
7                     Accrual Basis             Actual/360
8                            Coupon                   0.05
9           Business Day Convention                      F
10               Holiday Convention                   USGS
11           Payment Date Or Offset                     3M
12  Payment Business Day Convention                      F
13       Payment Holiday Convention                   USGS

Product (de-)serialization:

                               Name                  Value
0                      Product Type  PRODUCT_FIXED_ACCRUED
1                          Notional              1000000.0
2                          Currency                    USD
3                     Long Or Short                   LONG
4                    Effective Date             2026-03-26
5          Term Or Termination Date             2026-05-26
6                    Pay Or Receive                RECEIVE
7                     Accrual Basis             Actual/360
8                            Coupon                   0.05
9           Business Day Convention                      F
10               Holiday Convention                   USGS
11           Payment Date Or Offset                     3M
12  Payment Business Day Convention                      F
13       Payment Holiday Convention                   USGS

### Product Overnight Composite Index

In [4]:
print("Product creation and display:")
effecitve_date = '2026-03-26'
termination_date = '2026-05-26'
pay_or_rec = "receive"
on_composite_index = "USD-SOFR-COMPOUND"
spread = 0.001
currency = 'USD'
notional = 1e6
prod_on_composite_index_cashflow_default = qfCreateProductOvernightCompositeIndexCashflow(
    effecitve_date,
    termination_date,
    pay_or_rec,
    on_composite_index,
    spread,
    currency,
    notional)
display(qfDisplayProduct(prod_on_composite_index_cashflow_default))
accrual_basis = "Actual/Actual (ISDA)"
pay_offset = "2D"
pay_business_day_convention = "F"
pay_holiday_convention = "USGS"
lookback_window = "1D"
rate_cutoff = "0D"
prod_on_composite_index_cashflow_customized = qfCreateProductOvernightCompositeIndexCashflow(
    effecitve_date,
    termination_date,
    pay_or_rec,
    on_composite_index,
    spread,
    currency,
    notional,
    accrual_basis,
    pay_offset,
    pay_business_day_convention,
    pay_holiday_convention,
    lookback_window,
    rate_cutoff)
display(qfDisplayProduct(prod_on_composite_index_cashflow_customized))
print("Product (de-)serialization:")
# serialize
path = 'product_overnight_composite_index_cashflow.pickle'
qfWriteProductToFile(prod_on_composite_index_cashflow_customized, path)
# deserialize
prod_on_composite_index_cashflow_customized_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_on_composite_index_cashflow_customized_retrieved))
# house keeping
os.remove(path)

Product creation and display:

,Name,Value
0,Product Type,PRODUCT_OVERNIGHT_COMPOSITE_INDEX_CASHFLOW
1,Notional,1000000.0
2,Currency,USD
3,Long Or Short,LONG
4,Effective Date,2026-03-26
5,Term Or Termination Date,2026-05-26
6,Pay Or Receive,RECEIVE
7,ON Composite Index,USD-SOFR-COMPOUND
8,Spread,0.0
9,Accrual Basis,Actual/360
10,Payment Date Or Offset,0D
11,Payment Business Day Convention,NONE
12,Payment Holiday Convention,NONE
13,Rate Cutoff,0D
14,Lookback Window,0D

,Name,Value
0,Product Type,PRODUCT_OVERNIGHT_COMPOSITE_INDEX_CASHFLOW
1,Notional,1000000.0
2,Currency,USD
3,Long Or Short,LONG
4,Effective Date,2026-03-26
5,Term Or Termination Date,2026-05-26
6,Pay Or Receive,RECEIVE
7,ON Composite Index,USD-SOFR-COMPOUND
8,Spread,0.0
9,Accrual Basis,Actual/Actual (ISDA)
10,Payment Date Or Offset,2D
11,Payment Business Day Convention,F
12,Payment Holiday Convention,USGS
13,Rate Cutoff,0D
14,Lookback Window,1D

Product (de-)serialization:

,Name,Value
0,Product Type,PRODUCT_OVERNIGHT_COMPOSITE_INDEX_CASHFLOW
1,Notional,1000000.0
2,Currency,USD
3,Long Or Short,LONG
4,Effective Date,2026-03-26
5,Term Or Termination Date,2026-05-26
6,Pay Or Receive,RECEIVE
7,ON Composite Index,USD-SOFR-COMPOUND
8,Spread,0.0
9,Accrual Basis,Actual/Actual (ISDA)
10,Payment Date Or Offset,2D
11,Payment Business Day Convention,F
12,Payment Holiday Convention,USGS
13,Rate Cutoff,1D
14,Lookback Window,0D

### Product IBOR Index

In [5]:
print("Product creation and display:")
effecitve_date = '2026-03-26'
term_or_termination_date = '3M'
pay_or_rec = "receive"
ibor_index = "USD-TERM-SOFR-PROXY-3M"
spread = 0.001
currency = 'USD'
notional = 1e6
prod_ibor_cashflow_default = qfCreateProductIborIndexCashflow(
    effecitve_date,
    term_or_termination_date,
    pay_or_rec,
    ibor_index,
    spread,
    currency,
    notional)
display(qfDisplayProduct(prod_ibor_cashflow_default))
termination_date = "2026-07-26"
accrual_basis = "Actual/Actual (ISDA)"
pay_offset = "2D"
pay_business_day_convention = "MF"
pay_holiday_convention = "NYC"
pay_in_advance = True
prod_ibor_cashflow_customized = qfCreateProductIborIndexCashflow(
    effecitve_date,
    termination_date,
    pay_or_rec,
    ibor_index,
    spread,
    currency,
    notional,
    accrual_basis,
    pay_offset,
    pay_business_day_convention,
    pay_holiday_convention,
    pay_in_advance)
display(qfDisplayProduct(prod_ibor_cashflow_customized))
print("Product (de-)serialization:")
# serialize
path = 'product_ibor_index_cashflow.pickle'
qfWriteProductToFile(prod_ibor_cashflow_customized, path)
# deserialize
prod_ibor_cashflow_customized_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_ibor_cashflow_customized_retrieved))
# house keeping
os.remove(path)

Product creation and display:

                               Name                        Value
0                      Product Type  PRODUCT_IBOR_INDEX_CASHFLOW
1                          Notional                    1000000.0
2                          Currency                          USD
3                     Long Or Short                         LONG
4                    Effective Date                   2026-03-26
5          Term Or Termination Date                           3M
6                    Pay Or Receive                      RECEIVE
7                        IBOR Index       USD-TERM-SOFR-PROXY-3M
8                            Spread                          0.0
9                     Accrual Basis                       Simple
10           Payment Date Or Offset                           0D
11  Payment Business Day Convention                         NONE
12       Payment Holiday Convention                         NONE
13                   Pay In Advance                        False

                               Name                        Value
0                      Product Type  PRODUCT_IBOR_INDEX_CASHFLOW
1                          Notional                    1000000.0
2                          Currency                          USD
3                     Long Or Short                         LONG
4                    Effective Date                   2026-03-26
5          Term Or Termination Date                   2026-07-26
6                    Pay Or Receive                      RECEIVE
7                        IBOR Index       USD-TERM-SOFR-PROXY-3M
8                            Spread                          0.0
9                     Accrual Basis         Actual/Actual (ISDA)
10           Payment Date Or Offset                           2D
11  Payment Business Day Convention                           MF
12       Payment Holiday Convention                          NYC
13                   Pay In Advance                         True

Product (de-)serialization:

                               Name                        Value
0                      Product Type  PRODUCT_IBOR_INDEX_CASHFLOW
1                          Notional                    1000000.0
2                          Currency                          USD
3                     Long Or Short                         LONG
4                    Effective Date                   2026-03-26
5          Term Or Termination Date                   2026-07-26
6                    Pay Or Receive                      RECEIVE
7                        IBOR Index       USD-TERM-SOFR-PROXY-3M
8                            Spread                          0.0
9                     Accrual Basis         Actual/Actual (ISDA)
10           Payment Date Or Offset                   2026-03-30
11  Payment Business Day Convention                           MF
12       Payment Holiday Convention                          NYC
13                   Pay In Advance                         True

### Product COMPOUNDED IBOR Index

In [6]:
print("Product creation and display:")
effecitve_date = '2026-03-26'
term_or_termination_date = '6M'
pay_or_rec = "receive"
ibor_index = "USD-LIBOR-BBA-3M"
calculation_period = "3M"
spread = 0.001
currency = 'USD'
notional = 1e6
prod_ibor_compoundin_cashflow_default = qfCreateProductIborCompoundingCashflow(
    effecitve_date,
    term_or_termination_date,
    pay_or_rec,
    ibor_index,
    spread,
    currency,
    notional,
    calculation_period)
display(qfDisplayProduct(prod_ibor_compoundin_cashflow_default))
termination_date = "2026-10-26"
accrual_basis = "Actual/Actual (ISDA)"
pay_offset = "2D"
pay_business_day_convention = "MF"
pay_holiday_convention = "NYC"
leverage = 1.5
prod_ibor_compoundin_cashflow_customized = qfCreateProductIborCompoundingCashflow(
    effecitve_date,
    termination_date,
    pay_or_rec,
    ibor_index,
    spread,
    currency,
    notional,
    calculation_period,
    leverage,
    pay_offset,
    pay_business_day_convention,
    pay_holiday_convention)
display(qfDisplayProduct(prod_ibor_compoundin_cashflow_customized))
# serialize
path = 'product_compounding_ibor_index_cashflow.pickle'
qfWriteProductToFile(prod_ibor_compoundin_cashflow_customized, path)
# deserialize
prod_compounding_ibor_cashflow_customized_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_compounding_ibor_cashflow_customized_retrieved))
# house keeping
os.remove(path)

Product creation and display:

                               Name                              Value
0                      Product Type  PRODUCT_IBOR_COMPOUNDING_CASHFLOW
1                          Notional                          1000000.0
2                          Currency                                USD
3                     Long Or Short                               LONG
4                    Effective Date                         2026-03-26
5          Term Or Termination Date                                 6M
6                    Pay Or Receive                            RECEIVE
7                        IBOR Index                   USD-LIBOR-BBA-3M
8                            Spread                                0.0
9                          Leverage                                1.0
10               Calculation Period                                 3M
11           Payment Date Or Offset                                 0D
12  Payment Business Day Convention                               NONE
13       Payment Holiday Convention                               NONE
14               Compounding Method                      FLAT_COMPOUND

                               Name                              Value
0                      Product Type  PRODUCT_IBOR_COMPOUNDING_CASHFLOW
1                          Notional                          1000000.0
2                          Currency                                USD
3                     Long Or Short                               LONG
4                    Effective Date                         2026-03-26
5          Term Or Termination Date                         2026-10-26
6                    Pay Or Receive                            RECEIVE
7                        IBOR Index                   USD-LIBOR-BBA-3M
8                            Spread                                0.0
9                          Leverage                                1.5
10               Calculation Period                                 3M
11           Payment Date Or Offset                                 2D
12  Payment Business Day Convention                                 MF
13       Payment Holiday Convention                                NYC
14               Compounding Method                      FLAT_COMPOUND

                               Name                              Value
0                      Product Type  PRODUCT_IBOR_COMPOUNDING_CASHFLOW
1                          Notional                          1000000.0
2                          Currency                                USD
3                     Long Or Short                               LONG
4                    Effective Date                         2026-03-26
5          Term Or Termination Date                         2026-10-26
6                    Pay Or Receive                            RECEIVE
7                        IBOR Index                   USD-LIBOR-BBA-3M
8                            Spread                                0.0
9                          Leverage                                1.5
10               Calculation Period                                 3M
11           Payment Date Or Offset                                 2D
12  Payment Business Day Convention                                 MF
13       Payment Holiday Convention                                NYC
14               Compounding Method                      FLAT_COMPOUND

### Product Interest Rate Stream

#### Fixed Accrued Steam

In [7]:
print("Product creation and display:")
effecitve_date = "2026-03-26"
term_or_termination_date = "2028-04-26"
pay_or_rec = "pay"
fixed_rate = 0.05
currency = "GBP"
notional = 1_000_000
business_day_convention = "MF"
holiday_convention = "LON"
index = None
accrual_basis = "Actual/Actual (ISDA)"
accrual_period = "6M"
pay_offset = "2D"
pay_business_day_convention = "MF"
pay_holiday_convention = "LON"
schedule_generation_rule = "BACKWARD"
next_to_last_date = "2028-03-26"
prod_irs_fa = qfCreateProductInterestRateStream(
    effective_date=effecitve_date,
    term_or_terminatino_date=term_or_termination_date,
    pay_or_rec=pay_or_rec,
    fixed_rate_or_spread=fixed_rate,
    currency=currency,
    notional=notional,
    business_day_convention=business_day_convention,
    holiday_convention=holiday_convention,
    index=index,
    accrual_basis=accrual_basis,
    accrual_period=accrual_period,
    payment_date_or_offset=pay_offset,
    pay_business_day_convention=pay_business_day_convention,
    pay_holiday_convention=pay_holiday_convention,
    schedule_generation_rule=schedule_generation_rule,
    next_to_last_date=next_to_last_date)
display(qfDisplayProduct(prod_irs_fa))
# serialize
path = 'prod_irs_fa.pickle'
qfWriteProductToFile(prod_irs_fa, path)
# deserialize
prod_irs_fa_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_irs_fa_retrieved))
# house keeping
os.remove(path)

Product creation and display:

                Name                         Value
0       Product Type  PRODUCT_INTEREST_RATE_STREAM
1     Product 0 Type         PRODUCT_FIXED_ACCRUED
2   Product 0 Weight                           1.0
3     Product 1 Type         PRODUCT_FIXED_ACCRUED
4   Product 1 Weight                           1.0
5     Product 2 Type         PRODUCT_FIXED_ACCRUED
6   Product 2 Weight                           1.0
7     Product 3 Type         PRODUCT_FIXED_ACCRUED
8   Product 3 Weight                           1.0
9     Product 4 Type         PRODUCT_FIXED_ACCRUED
10  Product 4 Weight                           1.0

                Name                         Value
0       Product Type  PRODUCT_INTEREST_RATE_STREAM
1     Product 0 Type         PRODUCT_FIXED_ACCRUED
2   Product 0 Weight                           1.0
3     Product 1 Type         PRODUCT_FIXED_ACCRUED
4   Product 1 Weight                           1.0
5     Product 2 Type         PRODUCT_FIXED_ACCRUED
6   Product 2 Weight                           1.0
7     Product 3 Type         PRODUCT_FIXED_ACCRUED
8   Product 3 Weight                           1.0
9     Product 4 Type         PRODUCT_FIXED_ACCRUED
10  Product 4 Weight                           1.0

#### - Overnight Composite Index Stream

In [8]:
print("Product creation and display:")
effecitve_date = "2026-03-26"
term_or_termination_date = "2028-04-26"
pay_or_rec = "pay"
spread = 0.001
index = "GBP-SONIA-COMPOUND"
currency = "GBP"
notional = 1_000_000
business_day_convention = "MF"
holiday_convention = "LON"
accrual_period = "6M"
pay_offset = "2D"
pay_business_day_convention = "MF"
pay_holiday_convention = "LON"
schedule_generation_rule = "FORWARD"
lookback_window = "2D"
rate_cutoff = "0D"
end_of_month = False
first_regular_date = "2026-04-26"
prod_irs_on_composite = qfCreateProductInterestRateStream(
    effective_date=effecitve_date,
    term_or_terminatino_date=term_or_termination_date,
    pay_or_rec=pay_or_rec,
    fixed_rate_or_spread=spread,
    currency=currency,
    notional=notional,
    business_day_convention=business_day_convention,
    holiday_convention=holiday_convention,
    index=index,
    accrual_period=accrual_period,
    payment_date_or_offset=pay_offset,
    pay_business_day_convention=pay_business_day_convention,
    pay_holiday_convention=pay_holiday_convention,
    look_back_window=lookback_window,
    rate_cutoff=rate_cutoff,
    schedule_generation_rule=schedule_generation_rule,
    end_of_month=end_of_month,
    first_regular_date=first_regular_date)
display(qfDisplayProduct(prod_irs_on_composite))
# serialize
path = 'prod_irs_on_composite.pickle'
qfWriteProductToFile(prod_irs_on_composite, path)
# deserialize
prod_irs_on_composite_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_irs_on_composite_retrieved))
# house keeping
os.remove(path)

Product creation and display:

                Name                                       Value
0       Product Type                PRODUCT_INTEREST_RATE_STREAM
1     Product 0 Type  PRODUCT_OVERNIGHT_COMPOSITE_INDEX_CASHFLOW
2   Product 0 Weight                                         1.0
3     Product 1 Type  PRODUCT_OVERNIGHT_COMPOSITE_INDEX_CASHFLOW
4   Product 1 Weight                                         1.0
5     Product 2 Type  PRODUCT_OVERNIGHT_COMPOSITE_INDEX_CASHFLOW
6   Product 2 Weight                                         1.0
7     Product 3 Type  PRODUCT_OVERNIGHT_COMPOSITE_INDEX_CASHFLOW
8   Product 3 Weight                                         1.0
9     Product 4 Type  PRODUCT_OVERNIGHT_COMPOSITE_INDEX_CASHFLOW
10  Product 4 Weight                                         1.0

                Name                                       Value
0       Product Type                PRODUCT_INTEREST_RATE_STREAM
1     Product 0 Type  PRODUCT_OVERNIGHT_COMPOSITE_INDEX_CASHFLOW
2   Product 0 Weight                                         1.0
3     Product 1 Type  PRODUCT_OVERNIGHT_COMPOSITE_INDEX_CASHFLOW
4   Product 1 Weight                                         1.0
5     Product 2 Type  PRODUCT_OVERNIGHT_COMPOSITE_INDEX_CASHFLOW
6   Product 2 Weight                                         1.0
7     Product 3 Type  PRODUCT_OVERNIGHT_COMPOSITE_INDEX_CASHFLOW
8   Product 3 Weight                                         1.0
9     Product 4 Type  PRODUCT_OVERNIGHT_COMPOSITE_INDEX_CASHFLOW
10  Product 4 Weight                                         1.0

#### - IBOR Stream

In [9]:
print("Product creation and display:")
effecitve_date = "2026-03-26"
term_or_termination_date = "2028-04-26"
pay_or_rec = "receive"
spread = 0.001
index = "GBP-LIBOR-BBA-3M"
currency = "GBP"
notional = 1_000_000
business_day_convention = "MF"
holiday_convention = "LON"
accrual_period = "3M"
pay_offset = "2D"
pay_business_day_convention = "MF"
pay_holiday_convention = "LON"
schedule_generation_rule = "FORWARD"
end_of_month = False
first_regular_date = "2026-04-26"
prod_irs_ibor = qfCreateProductInterestRateStream(
    effective_date=effecitve_date,
    term_or_terminatino_date=term_or_termination_date,
    pay_or_rec=pay_or_rec,
    fixed_rate_or_spread=spread,
    currency=currency,
    notional=notional,
    business_day_convention=business_day_convention,
    holiday_convention=holiday_convention,
    index=index,
    accrual_period=accrual_period,
    accrual_basis="Actual/360",
    payment_date_or_offset=pay_offset,
    pay_business_day_convention=pay_business_day_convention,
    pay_holiday_convention=pay_holiday_convention,
    schedule_generation_rule=schedule_generation_rule,
    end_of_month=end_of_month,
    first_regular_date=first_regular_date)
display(qfDisplayProduct(prod_irs_ibor))
# serialize
path = 'prod_irs_ibor.pickle'
qfWriteProductToFile(prod_irs_ibor, path)
# deserialize
prod_irs_ibor_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_irs_ibor_retrieved))
# house keeping
os.remove(path)

Product creation and display:

                Name                         Value
0       Product Type  PRODUCT_INTEREST_RATE_STREAM
1     Product 0 Type   PRODUCT_IBOR_INDEX_CASHFLOW
2   Product 0 Weight                           1.0
3     Product 1 Type   PRODUCT_IBOR_INDEX_CASHFLOW
4   Product 1 Weight                           1.0
5     Product 2 Type   PRODUCT_IBOR_INDEX_CASHFLOW
6   Product 2 Weight                           1.0
7     Product 3 Type   PRODUCT_IBOR_INDEX_CASHFLOW
8   Product 3 Weight                           1.0
9     Product 4 Type   PRODUCT_IBOR_INDEX_CASHFLOW
10  Product 4 Weight                           1.0
11    Product 5 Type   PRODUCT_IBOR_INDEX_CASHFLOW
12  Product 5 Weight                           1.0
13    Product 6 Type   PRODUCT_IBOR_INDEX_CASHFLOW
14  Product 6 Weight                           1.0
15    Product 7 Type   PRODUCT_IBOR_INDEX_CASHFLOW
16  Product 7 Weight                           1.0
17    Product 8 Type   PRODUCT_IBOR_INDEX_CASHFLOW
18  Product 8 Weight                           1.0

                Name                              Value
0       Product Type       PRODUCT_INTEREST_RATE_STREAM
1     Product 0 Type  PRODUCT_IBOR_COMPOUNDING_CASHFLOW
2   Product 0 Weight                                1.0
3     Product 1 Type  PRODUCT_IBOR_COMPOUNDING_CASHFLOW
4   Product 1 Weight                                1.0
5     Product 2 Type  PRODUCT_IBOR_COMPOUNDING_CASHFLOW
6   Product 2 Weight                                1.0
7     Product 3 Type  PRODUCT_IBOR_COMPOUNDING_CASHFLOW
8   Product 3 Weight                                1.0
9     Product 4 Type  PRODUCT_IBOR_COMPOUNDING_CASHFLOW
10  Product 4 Weight                                1.0
11    Product 5 Type  PRODUCT_IBOR_COMPOUNDING_CASHFLOW
12  Product 5 Weight                                1.0
13    Product 6 Type  PRODUCT_IBOR_COMPOUNDING_CASHFLOW
14  Product 6 Weight                                1.0
15    Product 7 Type  PRODUCT_IBOR_COMPOUNDING_CASHFLOW
16  Product 7 Weight                                1.0
17    Product 8 Type  PRODUCT_IBOR_COMPOUNDING_CASHFLOW
18  Product 8 Weight                                1.0

#### - Compounded IBOR Stream

In [10]:
print("Product creation and display:")
effecitve_date = "2026-03-26"
term_or_termination_date = "2028-04-26"
pay_or_rec = "receive"
spread = 0.001
index = "GBP-LIBOR-BBA-3M"
currency = "GBP"
notional = 1_000_000
business_day_convention = "MF"
holiday_convention = "LON"
accrual_period = "3M"
calculation_period = "6M"
leverage = 1.5
pay_offset = "2D"
pay_business_day_convention = "MF"
pay_holiday_convention = "LON"
schedule_generation_rule = "FORWARD"
compounding_method = "spread_exclusive_compound" 
end_of_month = False
first_regular_date = "2026-04-26"
prod_irs_compounded_ibor = qfCreateProductInterestRateStream(
    effective_date=effecitve_date,
    term_or_terminatino_date=term_or_termination_date,
    pay_or_rec=pay_or_rec,
    fixed_rate_or_spread=spread,
    currency=currency,
    notional=notional,
    business_day_convention=business_day_convention,
    holiday_convention=holiday_convention,
    index=index,
    leverage=leverage,
    accrual_period=accrual_period,
    accrual_basis="Actual/360",
    calculation_period=calculation_period,
    payment_date_or_offset=pay_offset,
    pay_business_day_convention=pay_business_day_convention,
    pay_holiday_convention=pay_holiday_convention,
    schedule_generation_rule=schedule_generation_rule,
    compoundg_method=compounding_method,
    end_of_month=end_of_month,
    first_regular_date=first_regular_date)
display(qfDisplayProduct(prod_irs_compounded_ibor))
# serialize
path = 'prod_irs_compounded_ibor.pickle'
qfWriteProductToFile(prod_irs_compounded_ibor, path)
# deserialize
prod_irs_compounded_ibor_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_irs_compounded_ibor_retrieved))
# house keeping
os.remove(path)

Product creation and display:

                Name                              Value
0       Product Type       PRODUCT_INTEREST_RATE_STREAM
1     Product 0 Type  PRODUCT_IBOR_COMPOUNDING_CASHFLOW
2   Product 0 Weight                                1.0
3     Product 1 Type  PRODUCT_IBOR_COMPOUNDING_CASHFLOW
4   Product 1 Weight                                1.0
5     Product 2 Type  PRODUCT_IBOR_COMPOUNDING_CASHFLOW
6   Product 2 Weight                                1.0
7     Product 3 Type  PRODUCT_IBOR_COMPOUNDING_CASHFLOW
8   Product 3 Weight                                1.0
9     Product 4 Type  PRODUCT_IBOR_COMPOUNDING_CASHFLOW
10  Product 4 Weight                                1.0
11    Product 5 Type  PRODUCT_IBOR_COMPOUNDING_CASHFLOW
12  Product 5 Weight                                1.0
13    Product 6 Type  PRODUCT_IBOR_COMPOUNDING_CASHFLOW
14  Product 6 Weight                                1.0
15    Product 7 Type  PRODUCT_IBOR_COMPOUNDING_CASHFLOW
16  Product 7 Weight                                1.0
17    Product 8 Type  PRODUCT_IBOR_COMPOUNDING_CASHFLOW
18  Product 8 Weight                                1.0

                Name                              Value
0       Product Type       PRODUCT_INTEREST_RATE_STREAM
1     Product 0 Type  PRODUCT_IBOR_COMPOUNDING_CASHFLOW
2   Product 0 Weight                                1.0
3     Product 1 Type  PRODUCT_IBOR_COMPOUNDING_CASHFLOW
4   Product 1 Weight                                1.0
5     Product 2 Type  PRODUCT_IBOR_COMPOUNDING_CASHFLOW
6   Product 2 Weight                                1.0
7     Product 3 Type  PRODUCT_IBOR_COMPOUNDING_CASHFLOW
8   Product 3 Weight                                1.0
9     Product 4 Type  PRODUCT_IBOR_COMPOUNDING_CASHFLOW
10  Product 4 Weight                                1.0
11    Product 5 Type  PRODUCT_IBOR_COMPOUNDING_CASHFLOW
12  Product 5 Weight                                1.0
13    Product 6 Type  PRODUCT_IBOR_COMPOUNDING_CASHFLOW
14  Product 6 Weight                                1.0
15    Product 7 Type  PRODUCT_IBOR_COMPOUNDING_CASHFLOW
16  Product 7 Weight                                1.0
17    Product 8 Type  PRODUCT_IBOR_COMPOUNDING_CASHFLOW
18  Product 8 Weight                                1.0