In [1]:
import sys, os
repo_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
if repo_root not in sys.path:
    sys.path.insert(0, repo_root)
print("Added to sys.path:", repo_root)
from fixedincomelib import *
print("Fixed Income Library is loaded.")
value_date = "2026-03-26"

Added to sys.path: /Users/tiffanyyan/Documents/GitHub/QuantBricker
Fixed Income Library is loaded.

### Product Cash Deposit

In [2]:
print("Product creation and display:")
### creation
effective_date = "2026-03-26"
termination_date = "2026-05-26"
pay_or_rec = "receive"
currency = "USD"
notional = 1e6
coupon = 0.05
accrual_basis = "Actual/360"
payment_offset = "2D"
prod_cash_deposit = qfCreateProductCashDeposit(
    effective_date,
    termination_date,
    pay_or_rec,
    currency,
    notional,
    coupon,
    accrual_basis,
    payment_offset)
display(qfDisplayProduct(prod_cash_deposit))
print("Product (de-)serialization:")
### serialization
path = 'prod_cash_deposit.pickle'
qfWriteProductToFile(prod_cash_deposit, path)
# deserialize
prod_cash_deposit_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_cash_deposit_retrieved))
# house keeping
os.remove(path)
### from data convention
print("Product From Data Convention:")
axis1 = "1Y"
values = 0.05
data_conv = "USD-CASH-DEPOSIT"
prod_cash_deposit_from_conv = qfCreateProductFromDataConvention(
    value_date,
    data_conv,
    axis1,
    values
)
display(qfDisplayProduct(prod_cash_deposit_from_conv))
path = 'prod_cash_deposit_from_conv.pickle'
qfWriteProductToFile(prod_cash_deposit_from_conv, path)
# deserialize
prod_cash_deposit_from_conv_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_cash_deposit_from_conv_retrieved))
# house keeping
os.remove(path)

Product creation and display:

                        Name                 Value
0               Product Type  PRODUCT_CASH_DEPOSIT
1                   Notional             1000000.0
2                   Currency                   USD
3              Long Or Short                  LONG
4             Effective Date            2026-03-26
5   Term Or Termination Date            2026-05-26
6             Pay Or Receive               RECEIVE
7                     Coupon                  0.05
8              Accrual Basis            Actual/360
9     Payment Date Or Offset                    2D
10   Business Day Convention                  NONE
11        Holiday Convention                  NONE

Product (de-)serialization:

                        Name                 Value
0               Product Type  PRODUCT_CASH_DEPOSIT
1                   Notional             1000000.0
2                   Currency                   USD
3              Long Or Short                  LONG
4             Effective Date            2026-03-26
5   Term Or Termination Date            2026-05-26
6             Pay Or Receive               RECEIVE
7                     Coupon                  0.05
8              Accrual Basis            Actual/360
9     Payment Date Or Offset                    2D
10   Business Day Convention                     P
11        Holiday Convention                  NONE

Product From Data Convention:

                        Name                 Value
0               Product Type  PRODUCT_CASH_DEPOSIT
1                   Notional            10000000.0
2                   Currency                   USD
3              Long Or Short                  LONG
4             Effective Date            2026-03-26
5   Term Or Termination Date                    1Y
6             Pay Or Receive               RECEIVE
7                     Coupon                  0.05
8              Accrual Basis            Actual/360
9     Payment Date Or Offset                    0D
10   Business Day Convention                  NONE
11        Holiday Convention                  NONE

                        Name                 Value
0               Product Type  PRODUCT_CASH_DEPOSIT
1                   Notional            10000000.0
2                   Currency                   USD
3              Long Or Short                  LONG
4             Effective Date            2026-03-26
5   Term Or Termination Date                    1Y
6             Pay Or Receive               RECEIVE
7                     Coupon                  0.05
8              Accrual Basis            Actual/360
9     Payment Date Or Offset                    0D
10   Business Day Convention                     P
11        Holiday Convention                  NONE

### Product FRA / Fixings

In [3]:
print("Product creation and display:")
### creation
effective_date = "2026-03-26"
termination_date = "2026-05-26"
pay_or_rec = "receive"
currency = "USD"
notional = 1e6
coupon = 0.05
ibor_index = "SOFR-1B"
payment_offset = "2D"
prod_fra_or_fixings = qfCreateProductFRA(
    effective_date,
    termination_date,
    pay_or_rec,
    currency,
    notional,
    coupon,
    ibor_index,
    payment_offset)
display(qfDisplayProduct(prod_fra_or_fixings))
print("Product (de-)serialization:")
### serialization
path = 'prod_fra_or_fixings.pickle'
qfWriteProductToFile(prod_fra_or_fixings, path)
# deserialize
prod_fra_or_fixings_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_fra_or_fixings_retrieved))
# house keeping
os.remove(path)
### from data convention
print("Product From Data Convention:")
axis1 = "1D"
values = 0.05
data_conv = "SOFR-1B-FRA"
prod_fra_or_fixings_from_conv = qfCreateProductFromDataConvention(
    value_date,
    data_conv,
    axis1,
    values
)
display(qfDisplayProduct(prod_fra_or_fixings_from_conv))
path = 'prod_fra_or_fixings_from_conv.pickle'
qfWriteProductToFile(prod_fra_or_fixings_from_conv, path)
# deserialize
prod_fra_or_fixings_from_conv_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_fra_or_fixings_from_conv_retrieved))
# house keeping
os.remove(path)

Product creation and display:

                        Name                  Value
0               Product Type  PRODUCT_FRA_OR_FIXING
1                   Notional              1000000.0
2                   Currency                    USD
3              Long Or Short                   LONG
4             Effective Date             2026-03-26
5   Term Or Termination Date             2026-05-26
6             Pay Or Receive                RECEIVE
7                   Currency                    USD
8                   Currency              1000000.0
9                     Coupon                   0.05
10                IBOR Index                SOFR-1B
11    Payment Date Or Offset                     2D
12     FRA Discounting Style                   ISDA

Product (de-)serialization:

                        Name                  Value
0               Product Type  PRODUCT_FRA_OR_FIXING
1                   Notional              1000000.0
2                   Currency                    USD
3              Long Or Short                   LONG
4             Effective Date             2026-03-26
5   Term Or Termination Date             2026-05-26
6             Pay Or Receive                RECEIVE
7                   Currency                    USD
8                   Currency              1000000.0
9                     Coupon                   0.05
10                IBOR Index                SOFR-1B
11    Payment Date Or Offset             2026-05-28
12     FRA Discounting Style                   ISDA

Product From Data Convention:

                        Name                  Value
0               Product Type  PRODUCT_FRA_OR_FIXING
1                   Notional              1000000.0
2                   Currency                    USD
3              Long Or Short                   LONG
4             Effective Date             2026-03-27
5   Term Or Termination Date                     1D
6             Pay Or Receive                RECEIVE
7                   Currency                    USD
8                   Currency              1000000.0
9                     Coupon                   0.05
10                IBOR Index                SOFR-1B
11    Payment Date Or Offset                     0D
12     FRA Discounting Style                   ISDA

                        Name                  Value
0               Product Type  PRODUCT_FRA_OR_FIXING
1                   Notional              1000000.0
2                   Currency                    USD
3              Long Or Short                   LONG
4             Effective Date             2026-03-27
5   Term Or Termination Date                     1D
6             Pay Or Receive                RECEIVE
7                   Currency                    USD
8                   Currency              1000000.0
9                     Coupon                   0.05
10                IBOR Index                SOFR-1B
11    Payment Date Or Offset             2026-03-30
12     FRA Discounting Style                   ISDA

### Product Overnight Index Future

In [4]:
print("Product creation and display:")
### creation
effective_date = "2026-03-26"
term_or_termination_date = "3M"
long_or_short = "long"
amount = 1e4
on_composite_index = "USD-SOFR-COMPOUND"
strike = 0.05
payment_offset = "2D"
prod_overnight_index_future = qfCreateProductOvernightIndexFuture(
    effective_date,
    term_or_termination_date,
    long_or_short,
    amount,
    on_composite_index,
    strike,
    payment_offset)
display(qfDisplayProduct(prod_overnight_index_future))
print("Product (de-)serialization:")
### serialization
path = 'prod_overnight_index_future.pickle'
qfWriteProductToFile(prod_overnight_index_future, path)
# deserialize
prod_overnight_index_future_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_overnight_index_future_retrieved))
# house keeping
os.remove(path)
### from data convention
print("Product From Data Convention:")
axis1 = "2026-03-26 x 3M"
values = 98
data_conv = "SOFR-FUTURE-3M"
prod_on_index_future_from_conv = qfCreateProductFromDataConvention(
    value_date,
    data_conv,
    axis1,
    values
)
display(qfDisplayProduct(prod_on_index_future_from_conv))
path = 'prod_on_index_future_from_conv.pickle'
qfWriteProductToFile(prod_on_index_future_from_conv, path)
# deserialize
prod_on_index_future_from_conv_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_on_index_future_from_conv_retrieved))
# house keeping
os.remove(path)

Product creation and display:

                               Name                           Value
0                      Product Type  PRODUCT_OVERNIGHT_INDEX_FUTURE
1                          Notional                             0.0
2                          Currency                             USD
3                     Long Or Short                            LONG
4                    Effective Date                      2026-03-26
5   Termination Or Termination Date                              3M
6                     Long Or Short                            long
7                            Amount                         10000.0
8                ON Composite Index               USD-SOFR-COMPOUND
9                            Strike                            0.05
10           Payment Date Or Offset                              2D
11  Payment Business Day Convention                               F
12       Payment Holiday Convention                            USGS
13             Contractual Notional                       1000000.0
14                      Basis Point                            25.0
15                  Lookback Window                              0D
16                      Rate CutOff                              0D

Product (de-)serialization:

                               Name                           Value
0                      Product Type  PRODUCT_OVERNIGHT_INDEX_FUTURE
1                          Notional                             0.0
2                          Currency                             USD
3                     Long Or Short                            LONG
4                    Effective Date                      2026-03-26
5   Termination Or Termination Date                              3M
6                     Long Or Short                            long
7                            Amount                         10000.0
8                ON Composite Index               USD-SOFR-COMPOUND
9                            Strike                            0.05
10           Payment Date Or Offset                              2D
11  Payment Business Day Convention                               F
12       Payment Holiday Convention                            USGS
13             Contractual Notional                       1000000.0
14                      Basis Point                            25.0
15                  Lookback Window                              0D
16                      Rate CutOff                              0D

Product From Data Convention:

                               Name                           Value
0                      Product Type  PRODUCT_OVERNIGHT_INDEX_FUTURE
1                          Notional                             0.0
2                          Currency                             USD
3                     Long Or Short                            LONG
4                    Effective Date                      2026-03-26
5   Termination Or Termination Date                              3M
6                     Long Or Short                            long
7                            Amount                             1.0
8                ON Composite Index               USD-SOFR-COMPOUND
9                            Strike                              98
10           Payment Date Or Offset                              1D
11  Payment Business Day Convention                              MF
12       Payment Holiday Convention                            USGS
13             Contractual Notional                       1000000.0
14                      Basis Point                            25.0
15                  Lookback Window                              0D
16                      Rate CutOff                              0D

                               Name                           Value
0                      Product Type  PRODUCT_OVERNIGHT_INDEX_FUTURE
1                          Notional                             0.0
2                          Currency                             USD
3                     Long Or Short                            LONG
4                    Effective Date                      2026-03-26
5   Termination Or Termination Date                              3M
6                     Long Or Short                            long
7                            Amount                             1.0
8                ON Composite Index               USD-SOFR-COMPOUND
9                            Strike                              98
10           Payment Date Or Offset                              1D
11  Payment Business Day Convention                              MF
12       Payment Holiday Convention                            USGS
13             Contractual Notional                       1000000.0
14                      Basis Point                            25.0
15                  Lookback Window                              0D
16                      Rate CutOff                              0D

### Product Overnight Index Swap

In [5]:
print("Product creation and display:")
### creation
effective_date = "2026-03-26"
term_or_termination_date = "5Y"
on_composite_index = "USD-SOFR-COMPOUND"
fixed_rate = 0.04
pay_or_rec = "receive"
notional = 1e6
accrual_period = "1Y"
accrual_basis = "Actual/360"
business_day_convention = "MF"
holiday_convention = "USGS"
prod_ois_swap = qfCreateProductOvernightIndexSwap(
    effective_date,
    term_or_termination_date,
    on_composite_index,
    fixed_rate,
    pay_or_rec,
    notional,
    accrual_period,
    accrual_basis,
    business_day_convention,
    holiday_convention)
display(qfDisplayProduct(prod_ois_swap))
print("Product (de-)serialization:")
### serialization
path = 'prod_ois_swap.pickle'
qfWriteProductToFile(prod_ois_swap, path)
# deserialize
prod_ois_swap_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_ois_swap_retrieved))
# house keeping
os.remove(path)
### from data convention
print("Product From Data Convention:")
axis1 = "2Y x 3Y"
values = 0.04
data_conv = "USD-SOFR-OIS"
prod_ois_from_conv = qfCreateProductFromDataConvention(
    value_date,
    data_conv,
    axis1,
    values
)
display(qfDisplayProduct(prod_ois_from_conv))
path = 'prod_ois_from_conv.pickle'
qfWriteProductToFile(prod_ois_from_conv, path)
# deserialize
prod_ois_from_conv_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_ois_from_conv_retrieved))
# house keeping
os.remove(path)

Product creation and display:

                               Name                         Value
0                      Product Type  PRODUCT_OVERNIGHT_INDEX_SWAP
1                          Notional                     1000000.0
2                          Currency                           USD
3                     Long Or Short                          LONG
4                    Effective Date                    2026-03-26
5          Term Or Termination Date                            5Y
6         Overnight Composite Index             USD-SOFR-COMPOUND
7                        Fixed Rate                          0.04
8                    Pay Or Receive                       RECEIVE
9                          Notional      {U.S. dollar: 5000000.0}
10                   Accrual Period                            1Y
11                    Accrual Basis                    Actual/360
12          Business Day Convention                            MF
13               Holiday Convention                          USGS
14         Schedule Generation Rule                             0
15      Floating Leg Accrual Period                            1Y
16                   Payment Offset                            0D
17  Payment Business Day Convention                            MF
18       Payment Holiday Convention                          USGS
19                  Lookback Window                            0D
20                      Rate CutOff                            0D
21               First Regular Date                     null date
22                Next To Last Date                     null date

Product (de-)serialization:

                               Name                         Value
0                      Product Type  PRODUCT_OVERNIGHT_INDEX_SWAP
1                          Notional                     1000000.0
2                          Currency                           USD
3                     Long Or Short                          LONG
4                    Effective Date                    2026-03-26
5          Term Or Termination Date                            5Y
6         Overnight Composite Index             USD-SOFR-COMPOUND
7                        Fixed Rate                          0.04
8                    Pay Or Receive                       RECEIVE
9                          Notional      {U.S. dollar: 5000000.0}
10                   Accrual Period                            1Y
11                    Accrual Basis                    Actual/360
12          Business Day Convention                            MF
13               Holiday Convention                          USGS
14         Schedule Generation Rule                             0
15      Floating Leg Accrual Period                            1Y
16                   Payment Offset                            0D
17  Payment Business Day Convention                            MF
18       Payment Holiday Convention                          USGS
19                  Lookback Window                            0D
20                      Rate CutOff                            0D
21               First Regular Date                     null date
22                Next To Last Date                     null date

Product From Data Convention:

                               Name                         Value
0                      Product Type  PRODUCT_OVERNIGHT_INDEX_SWAP
1                          Notional                    10000000.0
2                          Currency                           USD
3                     Long Or Short                          LONG
4                    Effective Date                    2028-03-30
5          Term Or Termination Date                            3Y
6         Overnight Composite Index             USD-SOFR-COMPOUND
7                        Fixed Rate                          0.04
8                    Pay Or Receive                       RECEIVE
9                          Notional     {U.S. dollar: 40000000.0}
10                   Accrual Period                            1Y
11                    Accrual Basis                    Actual/360
12          Business Day Convention                            MF
13               Holiday Convention                           NYC
14         Schedule Generation Rule                             0
15      Floating Leg Accrual Period                            1Y
16                   Payment Offset                            2D
17  Payment Business Day Convention                            MF
18       Payment Holiday Convention                           NYC
19                  Lookback Window                            0D
20                      Rate CutOff                            0D
21               First Regular Date                     null date
22                Next To Last Date                     null date

                               Name                         Value
0                      Product Type  PRODUCT_OVERNIGHT_INDEX_SWAP
1                          Notional                    10000000.0
2                          Currency                           USD
3                     Long Or Short                          LONG
4                    Effective Date                    2028-03-30
5          Term Or Termination Date                            3Y
6         Overnight Composite Index             USD-SOFR-COMPOUND
7                        Fixed Rate                          0.04
8                    Pay Or Receive                       RECEIVE
9                          Notional     {U.S. dollar: 40000000.0}
10                   Accrual Period                            1Y
11                    Accrual Basis                    Actual/360
12          Business Day Convention                            MF
13               Holiday Convention                           NYC
14         Schedule Generation Rule                             0
15      Floating Leg Accrual Period                            1Y
16                   Payment Offset                            2D
17  Payment Business Day Convention                            MF
18       Payment Holiday Convention                           NYC
19                  Lookback Window                            0D
20                      Rate CutOff                            0D
21               First Regular Date                     null date
22                Next To Last Date                     null date

### Product Overnight Index Basis Swap

In [3]:
print("Product creation and display:")
### creation
effective_date = "2026-03-26"
term_or_termination_date = "5Y"
on_composite_index = "USD-SOFR-COMPOUND"
ibor_index = "USD-LIBOR-BBA-3M"
spread = 0.002
pay_or_rec_floating_leg = "receive"
notional = 1e6
accrual_period = "1Y"
accrual_basis = "Actual/360"
business_day_convention = "MF"
holiday_convention = "USGS"
schedue_rule = "BACKWARD"
payment_offset = "2D"
pay_business_day_convention = "MF"
pay_holiday_convention = "NYC"
prod_ois_basis_swap = qfCreateProductOvernightIndexBasisSwap(
    effective_date,
    term_or_termination_date,
    on_composite_index,
    ibor_index,
    spread,
    pay_or_rec_floating_leg,
    notional,
    accrual_period,
    business_day_convention,
    holiday_convention,
    schedue_rule,
    accrual_basis,
    accrual_basis,
    payment_offset,
    pay_business_day_convention,
    pay_holiday_convention)
display(qfDisplayProduct(prod_ois_basis_swap))
print("Product (de-)serialization:")
### serialization
path = 'prod_ois_basis_swap.pickle'
qfWriteProductToFile(prod_ois_basis_swap, path)
# deserialize
prod_ois_basis_swap_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_ois_basis_swap_retrieved))
# house keeping
os.remove(path)
### from data convention
print("Product From Data Convention:")
axis1 = "2Y x 3Y"
values = 0.04
data_conv = "USD-SOFR-OIS"
prod_ois_from_conv = qfCreateProductFromDataConvention(
    value_date,
    data_conv,
    axis1,
    values
)
display(qfDisplayProduct(prod_ois_from_conv))
path = 'prod_ois_from_conv.pickle'
qfWriteProductToFile(prod_ois_from_conv, path)
# deserialize
prod_ois_from_conv_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_ois_from_conv_retrieved))
# house keeping
os.remove(path)

Product creation and display:

                                 Name                               Value
0                        Product Type  PRODUCT_OVERNIGHT_INDEX_BASIS_SWAP
1                            Notional                           1000000.0
2                            Currency                                 USD
3                       Long Or Short                                LONG
4                      Effective Date                          2026-03-26
5            Term Or Termination Date                                  5Y
6                  ON Composite Index                   USD-SOFR-COMPOUND
7                          IBOR Index                    USD-LIBOR-BBA-3M
8                              Spread                               0.002
9   Pay Or Receive ON Composite Index                             RECEIVE
10                           Notional            {U.S. dollar: 5000000.0}
11                     Accrual Period                                  1Y
12            Business Day Convention                                  MF
13                 Holiday Convention                                USGS
14           Schedule Generation Rule                                   0
15               ON Leg Accrual Basis                          Actual/360
16              IBOR LegAccrual Basis                          Actual/360
17                     Payment Offset                                  2D
18    Payment Business Day Convention                                  MF
19         Payment Holiday Convention                                 NYC
20                    Lookback Window                                  0D
21                        Rate CutOff                                  0D
22                 First Regular Date                           null date
23                  Next To Last Date                           null date

Product (de-)serialization:

                                 Name                               Value
0                        Product Type  PRODUCT_OVERNIGHT_INDEX_BASIS_SWAP
1                            Notional                           1000000.0
2                            Currency                                 USD
3                       Long Or Short                                LONG
4                      Effective Date                          2026-03-26
5            Term Or Termination Date                                  5Y
6                  ON Composite Index                   USD-SOFR-COMPOUND
7                          IBOR Index                    USD-LIBOR-BBA-3M
8                              Spread                               0.002
9   Pay Or Receive ON Composite Index                             RECEIVE
10                           Notional            {U.S. dollar: 5000000.0}
11                     Accrual Period                                  1Y
12            Business Day Convention                                  MF
13                 Holiday Convention                                USGS
14           Schedule Generation Rule                                   0
15               ON Leg Accrual Basis                          Actual/360
16              IBOR LegAccrual Basis                          Actual/360
17                     Payment Offset                                  2D
18    Payment Business Day Convention                                  MF
19         Payment Holiday Convention                                 NYC
20                    Lookback Window                                  0D
21                        Rate CutOff                                  0D
22                 First Regular Date                           null date
23                  Next To Last Date                           null date

Product From Data Convention:

                               Name                         Value
0                      Product Type  PRODUCT_OVERNIGHT_INDEX_SWAP
1                          Notional                    10000000.0
2                          Currency                           USD
3                     Long Or Short                          LONG
4                    Effective Date                    2028-03-30
5          Term Or Termination Date                            3Y
6         Overnight Composite Index             USD-SOFR-COMPOUND
7                        Fixed Rate                          0.04
8                    Pay Or Receive                       RECEIVE
9                          Notional     {U.S. dollar: 40000000.0}
10                   Accrual Period                            1Y
11                    Accrual Basis                    Actual/360
12          Business Day Convention                            MF
13               Holiday Convention                           NYC
14         Schedule Generation Rule                             0
15      Floating Leg Accrual Period                            1Y
16                   Payment Offset                            2D
17  Payment Business Day Convention                            MF
18       Payment Holiday Convention                           NYC
19                  Lookback Window                            0D
20                      Rate CutOff                            0D
21               First Regular Date                     null date
22                Next To Last Date                     null date

                               Name                         Value
0                      Product Type  PRODUCT_OVERNIGHT_INDEX_SWAP
1                          Notional                    10000000.0
2                          Currency                           USD
3                     Long Or Short                          LONG
4                    Effective Date                    2028-03-30
5          Term Or Termination Date                            3Y
6         Overnight Composite Index             USD-SOFR-COMPOUND
7                        Fixed Rate                          0.04
8                    Pay Or Receive                       RECEIVE
9                          Notional     {U.S. dollar: 40000000.0}
10                   Accrual Period                            1Y
11                    Accrual Basis                    Actual/360
12          Business Day Convention                            MF
13               Holiday Convention                           NYC
14         Schedule Generation Rule                             0
15      Floating Leg Accrual Period                            1Y
16                   Payment Offset                            2D
17  Payment Business Day Convention                            MF
18       Payment Holiday Convention                           NYC
19                  Lookback Window                            0D
20                      Rate CutOff                            0D
21               First Regular Date                     null date
22                Next To Last Date                     null date

#### Product OIS Basis Swap

In [2]:
print("Product creation and display:")
### creation
effective_date = "2026-03-26"
term_or_termination_date = "5Y"
basis_leg_on_composite_index = "USD-Federal Funds-H.15-COMPOUND"
reference_leg_on_composite_index = "USD-SOFR-COMPOUND"
spread = 0.002
basis_leg_pay_or_rec = "receive"
notional = 1e6
accrual_period = "1Y"
accrual_basis = "Actual/360"
business_day_convention = "MF"
holiday_convention = "USGS"
schedue_rule = "BACKWARD"
payment_offset = "2D"
pay_business_day_convention = "MF"
pay_holiday_convention = "NYC"
prod_ois_ois_basis_swap = qfCreateProductOISBasisSwap(
    effective_date,
    term_or_termination_date,
    basis_leg_on_composite_index,
    reference_leg_on_composite_index,
    spread,
    basis_leg_pay_or_rec,
    notional,
    accrual_period,
    business_day_convention,
    holiday_convention,
    schedue_rule,
    accrual_basis,
    accrual_basis,
    payment_offset,
    pay_business_day_convention,
    pay_holiday_convention,
    )
display(qfDisplayProduct(prod_ois_ois_basis_swap))
print("Product (de-)serialization:")
### serialization
path = 'prod_ois_ois_basis_swap.pickle'
qfWriteProductToFile(prod_ois_ois_basis_swap, path)
# deserialize
prod_ois_ois_basis_swap_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_ois_ois_basis_swap_retrieved))
# house keeping
os.remove(path)
### from data convention
print("Product From Data Convention:")
axis1 = "2Y x 3Y"
values = 0.04
data_conv = "USD-SOFR-AVG-OVER-USD-SOFR-AVERAGE-BASIS-SWAP"
prod_ois_ois_basis_swap_from_conv = qfCreateProductFromDataConvention(
    value_date,
    data_conv,
    axis1,
    values
)
display(qfDisplayProduct(prod_ois_ois_basis_swap_from_conv))
path = 'prod_ois_ois_basis_swap_from_conv.pickle'
qfWriteProductToFile(prod_ois_ois_basis_swap_from_conv, path)
# deserialize
prod_ois_ois_basis_swap_from_conv_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_ois_ois_basis_swap_from_conv_retrieved))
# house keeping
os.remove(path)

Product creation and display:

                               Name                            Value
0                      Product Type           PRODUCT_OIS_BASIS_SWAP
1                          Notional                        1000000.0
2                          Currency                              USD
3                     Long Or Short                             LONG
4                    Effective Date                       2026-03-26
5          Term Or Termination Date                               5Y
6          Basis ON Composite Index  USD-FEDERAL FUNDS-H.15-COMPOUND
7      Reference ON Composite Index                USD-SOFR-COMPOUND
8                            Spread                            0.002
9                    Pay Or Receive                          RECEIVE
10                         Notional                        5000000.0
11                   Accrual Period                               1Y
12          Business Day Convention                               MF
13               Holiday Convention                             USGS
14         Schedule Generation Rule                                0
15          Basis Leg Accrual Basis                       Actual/360
16   Reference Leg LegAccrual Basis                       Actual/360
17                   Payment Offset                               2D
18  Payment Business Day Convention                               MF
19       Payment Holiday Convention                              NYC
20                  Lookback Window                               0D
21                      Rate CutOff                               0D
22               First Regular Date                        null date
23                Next To Last Date                        null date

Product (de-)serialization:

                               Name                            Value
0                      Product Type           PRODUCT_OIS_BASIS_SWAP
1                          Notional                        1000000.0
2                          Currency                              USD
3                     Long Or Short                             LONG
4                    Effective Date                       2026-03-26
5          Term Or Termination Date                               5Y
6          Basis ON Composite Index  USD-FEDERAL FUNDS-H.15-COMPOUND
7      Reference ON Composite Index                USD-SOFR-COMPOUND
8                            Spread                            0.002
9                    Pay Or Receive                          RECEIVE
10                         Notional                        5000000.0
11                   Accrual Period                               1Y
12          Business Day Convention                               MF
13               Holiday Convention                             USGS
14         Schedule Generation Rule                                0
15          Basis Leg Accrual Basis                       Actual/360
16   Reference Leg LegAccrual Basis                       Actual/360
17                   Payment Offset                               2D
18  Payment Business Day Convention                               MF
19       Payment Holiday Convention                              NYC
20                  Lookback Window                               0D
21                      Rate CutOff                               0D
22               First Regular Date                        null date
23                Next To Last Date                        null date

Product From Data Convention:

                               Name                   Value
0                      Product Type  PRODUCT_OIS_BASIS_SWAP
1                          Notional              10000000.0
2                          Currency                     USD
3                     Long Or Short                    LONG
4                    Effective Date              2028-03-30
5          Term Or Termination Date                      3Y
6          Basis ON Composite Index            USD-SOFR-AVG
7      Reference ON Composite Index        USD-SOFR-AVERAGE
8                            Spread                    0.04
9                    Pay Or Receive                 RECEIVE
10                         Notional             130000000.0
11                   Accrual Period                      3M
12          Business Day Convention                       F
13               Holiday Convention                    NONE
14         Schedule Generation Rule                       0
15          Basis Leg Accrual Basis              Actual/360
16   Reference Leg LegAccrual Basis              Actual/360
17                   Payment Offset                      2D
18  Payment Business Day Convention                      MF
19       Payment Holiday Convention                     NYC
20                  Lookback Window                      0D
21                      Rate CutOff                      0D
22               First Regular Date               null date
23                Next To Last Date               null date

                               Name                   Value
0                      Product Type  PRODUCT_OIS_BASIS_SWAP
1                          Notional              10000000.0
2                          Currency                     USD
3                     Long Or Short                    LONG
4                    Effective Date              2028-03-30
5          Term Or Termination Date                      3Y
6          Basis ON Composite Index            USD-SOFR-AVG
7      Reference ON Composite Index        USD-SOFR-AVERAGE
8                            Spread                    0.04
9                    Pay Or Receive                 RECEIVE
10                         Notional             120000000.0
11                   Accrual Period                      3M
12          Business Day Convention                       F
13               Holiday Convention                    NONE
14         Schedule Generation Rule                       0
15          Basis Leg Accrual Basis              Actual/360
16   Reference Leg LegAccrual Basis              Actual/360
17                   Payment Offset                      2D
18  Payment Business Day Convention                      MF
19       Payment Holiday Convention                     NYC
20                  Lookback Window                      0D
21                      Rate CutOff                      0D
22               First Regular Date               null date
23                Next To Last Date               null date

#### Product Overnight Index Currency Basis Swap (Non-MTM)

In [2]:
print("Product creation and display:")
### creation
effective_date = "2026-03-26"
term_or_termination_date = "5Y"
basis_leg_on_composite_index = "CAD-CORRA-COMPOUND"
reference_leg_on_composite_index = "USD-SOFR-COMPOUND"
spread = 0.002
basis_leg_pay_or_rec = "receive"
notional = 1e6
fx_index = "USD-CAD"
accrual_period = "1Y"
accrual_basis = "Actual/360"
business_day_convention = "MF"
holiday_convention = "USGS"
schedue_rule = "BACKWARD"
payment_offset = "2D"
pay_business_day_convention = "MF"
pay_holiday_convention = "TOR"
reference_accrual_period = "1Y"
reference_accrual_basis = "Actual/Actual (ISDA)"
reference_payment_offset = "2D"
reference_pay_business_day_convention = "F"
reference_pay_holiday_convention = "USGS"
prod_xccy_basis_swap = qfCreateProductOvernightIndexCurrencyBasisSwapNonMTM(
    effective_date,
    term_or_termination_date,
    basis_leg_on_composite_index,
    reference_leg_on_composite_index,
    basis_leg_pay_or_rec,
    notional,
    fx_index,
    accrual_period,
    accrual_basis,
    spread,
    schedue_rule,
    business_day_convention,
    holiday_convention,
    payment_offset,
    pay_business_day_convention,
    pay_holiday_convention,
    True,
    True,
    "2D",
    "0D",
    "",
    "",
    False,
    reference_accrual_period,
    reference_accrual_basis,
    reference_payment_offset,
    reference_pay_business_day_convention,
    reference_pay_holiday_convention)
display(qfDisplayProduct(prod_xccy_basis_swap))
print("Product (de-)serialization:")
### serialization
path = 'prod_xccy_basis_swap.pickle'
qfWriteProductToFile(prod_xccy_basis_swap, path)
# deserialize
prod_xccy_basis_swap_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_xccy_basis_swap_retrieved))
# house keeping
os.remove(path)
### from data convention
print("Product From Data Convention:")
axis1 = "2Y x 3Y"
values = 0.04
data_conv = "CAD-CORRA-COMPOUND-3M-OVER-USD-SOFR-COMPOUND-3M-OVERNIGHT-INDEX-CBS"
prod_xccy_basis_swap_from_conv = qfCreateProductFromDataConvention(
    value_date,
    data_conv,
    axis1,
    values
)
display(qfDisplayProduct(prod_xccy_basis_swap_from_conv))
path = 'prod_xccy_basis_swap_from_conv.pickle'
qfWriteProductToFile(prod_xccy_basis_swap_from_conv, path)
# deserialize
prod_xccy_basis_swap_from_conv_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_xccy_basis_swap_from_conv_retrieved))
# house keeping
os.remove(path)

Product creation and display:

,Name,Value
0,Product Type,PRODUCT_XCCY_BASIS_SWAP_NON_MTM
1,Currency (Basis),CAD
2,Long Or Short,LONG
3,Effective Date,2026-03-26
4,Term Or Termination Date,5Y
5,Basis Leg Index,CAD-CORRA-COMPOUND
6,Reference Leg Index,USD-SOFR-COMPOUND
7,Pay Or Receive,RECEIVE
8,Notional (Basis Leg),5000000.0
9,FX Index,USD-CAD
10,Accrual Period,1Y
11,Accrual Basis,Actual/360
12,Spread,0.002
13,Schedule Generation Rule,0
14,Business Day Convention,MF
15,Holiday Convention,USGS
16,Payment Offset,2D
17,Payment Business Day Convention,MF
18,Payment Holiday Convention,TOR
19,Exchange At Start,True
20,Exchange At End,True
21,Lookback Window,2D
22,Rate CutOff,0D
23,First Regular Date,null date
24,Next To Last Date,null date
25,End of Month,False
26,Reference Leg Accrual Period,1Y
27,Reference Leg Accrual Basis,Actual/Actual (ISDA)
28,Reference Leg Payment Offset,2D
29,Reference Leg Payment Business Day Convention,MF
30,Reference Leg Payment Holiday Convention,USGS

Product (de-)serialization:

,Name,Value
0,Product Type,PRODUCT_XCCY_BASIS_SWAP_NON_MTM
1,Currency (Basis),CAD
2,Long Or Short,LONG
3,Effective Date,2026-03-26
4,Term Or Termination Date,5Y
5,Basis Leg Index,CAD-CORRA-COMPOUND
6,Reference Leg Index,USD-SOFR-COMPOUND
7,Pay Or Receive,RECEIVE
8,Notional (Basis Leg),5000000.0
9,FX Index,USD-CAD
10,Accrual Period,1Y
11,Accrual Basis,Actual/360
12,Spread,0.002
13,Schedule Generation Rule,0
14,Business Day Convention,MF
15,Holiday Convention,USGS
16,Payment Offset,2D
17,Payment Business Day Convention,MF
18,Payment Holiday Convention,TOR
19,Exchange At Start,True
20,Exchange At End,True
21,Lookback Window,2D
22,Rate CutOff,0D
23,First Regular Date,null date
24,Next To Last Date,null date
25,End of Month,False
26,Reference Leg Accrual Period,1Y
27,Reference Leg Accrual Basis,Actual/Actual (ISDA)
28,Reference Leg Payment Offset,2D
29,Reference Leg Payment Business Day Convention,MF
30,Reference Leg Payment Holiday Convention,USGS

Product From Data Convention:

,Name,Value
0,Product Type,PRODUCT_XCCY_BASIS_SWAP_NON_MTM
1,Currency (Basis),CAD
2,Long Or Short,LONG
3,Effective Date,2028-03-30
4,Term Or Termination Date,3Y
5,Basis Leg Index,CAD-CORRA-COMPOUND
6,Reference Leg Index,USD-SOFR-COMPOUND
7,Pay Or Receive,RECEIVE
8,Notional (Basis Leg),130000000.0
9,FX Index,USD-CAD
10,Accrual Period,3M
11,Accrual Basis,Actual/365 (Fixed)
12,Spread,0.04
13,Schedule Generation Rule,0
14,Business Day Convention,F
15,Holiday Convention,TOR
16,Payment Offset,2D
17,Payment Business Day Convention,F
18,Payment Holiday Convention,TOR
19,Exchange At Start,True
20,Exchange At End,True
21,Lookback Window,0D
22,Rate CutOff,0D
23,First Regular Date,null date
24,Next To Last Date,null date
25,End of Month,None
26,Reference Leg Accrual Period,3M
27,Reference Leg Accrual Basis,Actual/360
28,Reference Leg Payment Offset,2D
29,Reference Leg Payment Business Day Convention,F
30,Reference Leg Payment Holiday Convention,NONE

,Name,Value
0,Product Type,PRODUCT_XCCY_BASIS_SWAP_NON_MTM
1,Currency (Basis),CAD
2,Long Or Short,LONG
3,Effective Date,2028-03-30
4,Term Or Termination Date,3Y
5,Basis Leg Index,CAD-CORRA-COMPOUND
6,Reference Leg Index,USD-SOFR-COMPOUND
7,Pay Or Receive,RECEIVE
8,Notional (Basis Leg),130000000.0
9,FX Index,USD-CAD
10,Accrual Period,3M
11,Accrual Basis,Actual/365 (Fixed)
12,Spread,0.04
13,Schedule Generation Rule,0
14,Business Day Convention,F
15,Holiday Convention,TOR
16,Payment Offset,2D
17,Payment Business Day Convention,F
18,Payment Holiday Convention,TOR
19,Exchange At Start,True
20,Exchange At End,True
21,Lookback Window,0D
22,Rate CutOff,0D
23,First Regular Date,null date
24,Next To Last Date,null date
25,End of Month,False
26,Reference Leg Accrual Period,3M
27,Reference Leg Accrual Basis,Actual/360
28,Reference Leg Payment Offset,2D
29,Reference Leg Payment Business Day Convention,F
30,Reference Leg Payment Holiday Convention,TOR