In [1]:
import sys, os
repo_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
if repo_root not in sys.path:
    sys.path.insert(0, repo_root)
print("Added to sys.path:", repo_root)
from fixedincomelib import *
print("Fixed Income Library is loaded.")
value_date = "2026-03-26"

Added to sys.path: /Users/nirvana/Documents/QuantBricker
Fixed Income Library is loaded.

### Product Generic Forward

In [2]:
print("Product creation and display:")
### creation
effective_date = "2026-03-26"
termination_date = "3M"
pay_or_rec = "receive"
currency = "USD"
notional = 1e6
index = "USD-LIBOR-BBA-3M-FLAT"
coupon = 0.05
accrual_basis = "Actual/360"
settlement_offset = "2D"
payment_offset = "2D"
business_day_convention = "MF"
holiday_convention = "NYC"
prod_generic_forward = qfCreateProductGenericForward(
    effective_date,
    termination_date,
    pay_or_rec,
    currency,
    notional,
    index,
    coupon,
    accrual_basis,
    settlement_offset,
    business_day_convention,
    holiday_convention,
    payment_offset,
    business_day_convention,
    holiday_convention,
    False)
display(qfDisplayProduct(prod_generic_forward))
print("Product (de-)serialization:")
### serialization
path = 'prod_generic_forward.pickle'
qfWriteProductToFile(prod_generic_forward, path)
# deserialize
prod_generic_forward_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_generic_forward_retrieved))
# house keeping
os.remove(path)
### from data convention
print("Product From Data Convention:")
axis1 = "1Y"
values = 0.05
data_conv = "USD-LIBOR-BBA-3M-FLAT-FWD"
prod_generic_forward_from_conv = qfCreateProductFromDataConvention(
    value_date,
    data_conv,
    axis1,
    values
)
display(qfDisplayProduct(prod_generic_forward_from_conv))
path = 'prod_generic_forward_from_conv.pickle'
qfWriteProductToFile(prod_generic_forward_from_conv, path)
# deserialize
prod_generic_forward_from_conv_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_generic_forward_from_conv_retrieved))
# house keeping
os.remove(path)

Product creation and display:

                               Name                    Value
0                      Product Type  PRODUCT_GENERIC_FORWARD
1                          Notional                1000000.0
2                          Currency                      USD
3                     Long Or Short                     LONG
4                    Effective Date               2026-03-26
5          Term Or Termination Date                       3M
6                        Pay Or Rec                  RECEIVE
7                          Currency                      USD
8                          Notional                1000000.0
9                            Coupon                     0.05
10                            Index    USD-LIBOR-BBA-3M-FLAT
11                    Accrual Basis               Actual/360
12                Settlement Offset                       2D
13          Business Day Convention                       MF
14               Holiday Convention                      NYC
15               Pay Date Or Offset                       2D
16  Payment Business Day Convention                       MF
17       Payment Holiday Convention                      NYC
18                     End Of Month                    False
19               Compounding Method               CONTINUOUS

Product (de-)serialization:

                               Name                    Value
0                      Product Type  PRODUCT_GENERIC_FORWARD
1                          Notional                1000000.0
2                          Currency                      USD
3                     Long Or Short                     LONG
4                    Effective Date               2026-03-26
5          Term Or Termination Date                       3M
6                        Pay Or Rec                  RECEIVE
7                          Currency                      USD
8                          Notional                1000000.0
9                            Coupon                     0.05
10                            Index    USD-LIBOR-BBA-3M-FLAT
11                    Accrual Basis               Actual/360
12                Settlement Offset                       2D
13          Business Day Convention                       MF
14               Holiday Convention                      NYC
15               Pay Date Or Offset                       2D
16  Payment Business Day Convention                       MF
17       Payment Holiday Convention                      NYC
18                     End Of Month                    False
19               Compounding Method               CONTINUOUS

Product From Data Convention:

                               Name                    Value
0                      Product Type  PRODUCT_GENERIC_FORWARD
1                          Notional               10000000.0
2                          Currency                      USD
3                     Long Or Short                     LONG
4                    Effective Date               2026-03-30
5          Term Or Termination Date                       1Y
6                        Pay Or Rec                  RECEIVE
7                          Currency                      USD
8                          Notional               10000000.0
9                            Coupon                     0.05
10                            Index    USD-LIBOR-BBA-3M-FLAT
11                    Accrual Basis       Actual/365 (Fixed)
12                Settlement Offset                       2D
13          Business Day Convention                        P
14               Holiday Convention                     NONE
15               Pay Date Or Offset                       0D
16  Payment Business Day Convention                        P
17       Payment Holiday Convention                     NONE
18                     End Of Month                    False
19               Compounding Method               CONTINUOUS

                               Name                    Value
0                      Product Type  PRODUCT_GENERIC_FORWARD
1                          Notional               10000000.0
2                          Currency                      USD
3                     Long Or Short                     LONG
4                    Effective Date               2026-03-30
5          Term Or Termination Date                       1Y
6                        Pay Or Rec                  RECEIVE
7                          Currency                      USD
8                          Notional               10000000.0
9                            Coupon                     0.05
10                            Index    USD-LIBOR-BBA-3M-FLAT
11                    Accrual Basis       Actual/365 (Fixed)
12                Settlement Offset                       2D
13          Business Day Convention                        P
14               Holiday Convention                     NONE
15               Pay Date Or Offset                       0D
16  Payment Business Day Convention                        P
17       Payment Holiday Convention                     NONE
18                     End Of Month                    False
19               Compounding Method               CONTINUOUS

### Generic Forward Spread

In [7]:
print("Product creation and display:")
### creation
effective_date = "2026-03-26"
termination_date = "3M"
pay_or_rec = "receive"
currency = "USD"
notional = 1e6
basis_index = "CAD"
reference_index = "USD"
spread = 0.001
accrual_basis = "Actual/360"
settlement_offset = "2D"
payment_offset = "2D"
business_day_convention = "MF"
holiday_convention = "NYC"
prod_generic_forward_spread = qfCreateProductGenericForwardSpread(
    effective_date,
    termination_date,
    pay_or_rec,
    currency,
    notional,
    spread,
    basis_index,
    reference_index,
    accrual_basis,
    settlement_offset,
    business_day_convention,
    holiday_convention,
    payment_offset,
    business_day_convention,
    holiday_convention,
    False)
display(qfDisplayProduct(prod_generic_forward_spread))
print("Product (de-)serialization:")
### serialization
path = 'prod_generic_forward_spread.pickle'
qfWriteProductToFile(prod_generic_forward_spread, path)
# deserialize
prod_generic_forward_spread_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_generic_forward_spread_retrieved))
# house keeping
os.remove(path)
### from data convention
print("Product From Data Convention:")
axis1 = "1Y x 3M"
values = 0.001
data_conv = "CAD-OVER-USD-GFS"
prod_generic_forward_spread_from_conv = qfCreateProductFromDataConvention(
    value_date,
    data_conv,
    axis1,
    values
)
display(qfDisplayProduct(prod_generic_forward_spread_from_conv))
path = 'prod_generic_forward_spread_from_conv.pickle'
qfWriteProductToFile(prod_generic_forward_spread_from_conv, path)
# deserialize
prod_generic_forward_spread_from_conv_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_generic_forward_spread_from_conv_retrieved))
# house keeping
os.remove(path)

Product creation and display:

                               Name                           Value
0                      Product Type  PRODUCT_GENERIC_FORWARD_SPREAD
1                          Notional                       1000000.0
2                          Currency                             USD
3                     Long Or Short                            LONG
4                    Effective Date                      2026-03-26
5          Term Or Termination Date                              3M
6                        Pay Or Rec                         RECEIVE
7                          Currency                             USD
8                          Notional                       1000000.0
9                            Spread                           0.001
10                      Basis Index                             CAD
11                  Reference Index                             USD
12                    Accrual Basis                      Actual/360
13                Settlement Offset                              2D
14          Business Day Convention                              MF
15               Holiday Convention                             NYC
16               Pay Date Or Offset                              2D
17  Payment Business Day Convention                              MF
18       Payment Holiday Convention                             NYC
19                     End Of Month                           False
20               Compounding Method                      CONTINUOUS
21      Reference Leg Accrual Basis                            None

Product (de-)serialization:

,Name,Value
0,Product Type,PRODUCT_GENERIC_FORWARD_SPREAD
1,Notional,1000000.0
2,Currency,USD
3,Long Or Short,LONG
4,Effective Date,2026-03-26
5,Term Or Termination Date,3M
6,Pay Or Rec,RECEIVE
7,Currency,USD
8,Notional,1000000.0
9,Spread,0.001
10,Basis Index,CAD
11,Reference Index,USD
12,Accrual Basis,Actual/360
13,Settlement Offset,<fixedincomelib.date.basics.TermOrDate object ...
14,Business Day Convention,MF
15,Holiday Convention,NYC
16,Pay Date Or Offset,2D
17,Payment Business Day Convention,MF
18,Payment Holiday Convention,NYC
19,End Of Month,False
20,Compounding Method,CONTINUOUS
21,Reference Leg Accrual Basis,Simple

Product From Data Convention:

                               Name                           Value
0                      Product Type  PRODUCT_GENERIC_FORWARD_SPREAD
1                          Notional                      10000000.0
2                          Currency                             CAD
3                     Long Or Short                            LONG
4                    Effective Date                      2027-03-30
5          Term Or Termination Date                              1Y
6                        Pay Or Rec                         RECEIVE
7                          Currency                             CAD
8                          Notional                      10000000.0
9                            Spread                           0.001
10                      Basis Index                             CAD
11                  Reference Index                             USD
12                    Accrual Basis              Actual/365 (Fixed)
13                Settlement Offset                              2D
14          Business Day Convention                               F
15               Holiday Convention                            NONE
16               Pay Date Or Offset                              0D
17  Payment Business Day Convention                               P
18       Payment Holiday Convention                            NONE
19                     End Of Month                           False
20               Compounding Method                      CONTINUOUS
21      Reference Leg Accrual Basis                            None

,Name,Value
0,Product Type,PRODUCT_GENERIC_FORWARD_SPREAD
1,Notional,10000000.0
2,Currency,CAD
3,Long Or Short,LONG
4,Effective Date,2027-03-30
5,Term Or Termination Date,1Y
6,Pay Or Rec,RECEIVE
7,Currency,CAD
8,Notional,10000000.0
9,Spread,0.001
10,Basis Index,CAD
11,Reference Index,USD
12,Accrual Basis,Actual/365 (Fixed)
13,Settlement Offset,<fixedincomelib.date.basics.TermOrDate object ...
14,Business Day Convention,F
15,Holiday Convention,NONE
16,Pay Date Or Offset,0D
17,Payment Business Day Convention,P
18,Payment Holiday Convention,NONE
19,End Of Month,False
20,Compounding Method,CONTINUOUS
21,Reference Leg Accrual Basis,Simple

### Product IBOR Spread Zero

In [2]:
print("Product creation and display:")
### creation
term_or_termination_date = "2026-03-26"
pay_or_rec = "receive"
currency = "USD"
notional = 1e4
spread = 0.001
basis_index = "USD-Federal Funds-H.15-1B"
reference_index = "USD-Federal Funds-H.15-1B-FLAT"
prod_iszr = qfCreateProductIBORZeroSpread(
    term_or_termination_date,
    pay_or_rec,
    currency,
    notional,
    spread,
    basis_index,
    reference_index)
display(qfDisplayProduct(prod_iszr))
print("Product (de-)serialization:")
### serialization
path = 'prod_overnight_index_future.pickle'
qfWriteProductToFile(prod_iszr, path)
# deserialize
prod_iszr_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_iszr_retrieved))
# house keeping
os.remove(path)
### from data convention
print("Product From Data Convention:")
axis1 = "1Y"
values = 0.05
data_conv = "USD-Federal Funds-H.15-1B-OVER-USD-Federal Funds H.15-1B-FLAT-ISZR"
prod_iszr_from_conv = qfCreateProductFromDataConvention(
    value_date,
    data_conv,
    axis1,
    values
)
display(qfDisplayProduct(prod_iszr_from_conv))
path = 'prod_iszr_from_conv.pickle'
qfWriteProductToFile(prod_iszr_from_conv, path)
# deserialize
prod_iszr_from_conv_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_iszr_from_conv_retrieved))
# house keeping
os.remove(path)

Product creation and display:

                Name                           Value
0       Product Type        PRODUCT_IBOR_ZERO_SPREAD
1           Notional                         10000.0
2           Currency                             USD
3      Long Or Short                            LONG
4   Termination Date                      2026-03-26
5         Pay Or Rec                         RECEIVE
6           Currency                             USD
7           Notional                         10000.0
8             Spread                           0.001
9        Basis Index       USD-FEDERAL FUNDS-H.15-1B
10   Reference Index  USD-FEDERAL FUNDS-H.15-1B-FLAT

Product (de-)serialization:

                Name                           Value
0       Product Type        PRODUCT_IBOR_ZERO_SPREAD
1           Notional                         10000.0
2           Currency                             USD
3      Long Or Short                            LONG
4   Termination Date                      2026-03-26
5         Pay Or Rec                         RECEIVE
6           Currency                             USD
7           Notional                         10000.0
8             Spread                           0.001
9        Basis Index       USD-FEDERAL FUNDS-H.15-1B
10   Reference Index  USD-FEDERAL FUNDS-H.15-1B-FLAT

Product From Data Convention:

                Name                           Value
0       Product Type        PRODUCT_IBOR_ZERO_SPREAD
1           Notional                         10000.0
2           Currency                             USD
3      Long Or Short                            LONG
4   Termination Date                      2027-03-26
5         Pay Or Rec                         RECEIVE
6           Currency                             USD
7           Notional                         10000.0
8             Spread                            0.05
9        Basis Index       USD-FEDERAL FUNDS-H.15-1B
10   Reference Index  USD-FEDERAL FUNDS-H.15-1B-FLAT

                Name                           Value
0       Product Type        PRODUCT_IBOR_ZERO_SPREAD
1           Notional                         10000.0
2           Currency                             USD
3      Long Or Short                            LONG
4   Termination Date                      2027-03-26
5         Pay Or Rec                         RECEIVE
6           Currency                             USD
7           Notional                         10000.0
8             Spread                            0.05
9        Basis Index       USD-FEDERAL FUNDS-H.15-1B
10   Reference Index  USD-FEDERAL FUNDS-H.15-1B-FLAT

### Product Generic Spread

In [3]:
print("Product creation and display:")
### creation
effective_date = "2026-03-23"
term_or_termination_date = "1Y"
pay_or_rec = "receive"
currency = "USD"
notional = 1e6
spread = 1e-3
basis_data_conv = "USD-SOFR-OIS"
reference_data_conv = "USD-SWAP-SEMI-BOND"
prod_gs = qfCreateProductGenericSpread(
    effective_date,
    term_or_termination_date,
    pay_or_rec,
    currency,
    notional,
    spread,
    basis_data_conv,
    reference_data_conv)
display(qfDisplayProduct(prod_gs))
print("Product (de-)serialization:")
### serialization
path = 'prod_overnight_index_future.pickle'
qfWriteProductToFile(prod_gs, path)
# deserialize
prod_gs_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_gs_retrieved))
# house keeping
os.remove(path)
### from data convention
print("Product From Data Convention:")
axis1 = "1Y"
values = 0.05
data_conv = "USD-SOFR-OIS-OVER-USD-SWAP-SEMI-BOND-G-SPD"
prod_gsp_from_conv = qfCreateProductFromDataConvention(
    value_date,
    data_conv,
    axis1,
    values
)
display(qfDisplayProduct(prod_gsp_from_conv))
path = 'prod_gsp_from_conv.pickle'
qfWriteProductToFile(prod_gsp_from_conv, path)
# deserialize
prod_gsp_from_conv_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_gsp_from_conv_retrieved))
# house keeping
os.remove(path)

Product creation and display:

                         Name                   Value
0                Product Type  PRODUCT_GENERIC_SPREAD
1                    Notional               1000000.0
2                    Currency                     USD
3               Long Or Short                    LONG
4              Effective Date              2026-03-23
5    Term Or Termination Date                      1Y
6                  Pay Or Rec                 RECEIVE
7                    Currency                     USD
8                    Notional               1000000.0
9                      Spread                   0.001
10      Basis Data Convention            USD-SOFR-OIS
11  Reference Data Convention            USD-SOFR-OIS

Product (de-)serialization:

                         Name                   Value
0                Product Type  PRODUCT_GENERIC_SPREAD
1                    Notional               1000000.0
2                    Currency                     USD
3               Long Or Short                    LONG
4              Effective Date              2026-03-23
5    Term Or Termination Date                      1Y
6                  Pay Or Rec                 RECEIVE
7                    Currency                     USD
8                    Notional               1000000.0
9                      Spread                   0.001
10      Basis Data Convention            USD-SOFR-OIS
11  Reference Data Convention            USD-SOFR-OIS

Product From Data Convention:

                         Name                   Value
0                Product Type  PRODUCT_GENERIC_SPREAD
1                    Notional              10000000.0
2                    Currency                     USD
3               Long Or Short                    LONG
4              Effective Date              2026-03-28
5    Term Or Termination Date                      1Y
6                  Pay Or Rec                 RECEIVE
7                    Currency                     USD
8                    Notional              10000000.0
9                      Spread                    0.05
10      Basis Data Convention            USD-SOFR-OIS
11  Reference Data Convention            USD-SOFR-OIS

                         Name                   Value
0                Product Type  PRODUCT_GENERIC_SPREAD
1                    Notional              10000000.0
2                    Currency                     USD
3               Long Or Short                    LONG
4              Effective Date              2026-03-28
5    Term Or Termination Date                      1Y
6                  Pay Or Rec                 RECEIVE
7                    Currency                     USD
8                    Notional              10000000.0
9                      Spread                    0.05
10      Basis Data Convention            USD-SOFR-OIS
11  Reference Data Convention            USD-SOFR-OIS

#### Product Swap Spread Basis Swap

In [2]:
print("Product creation and display:")
### creation
effective_date = "2026-03-23"
term_or_termination_date = "1Y"
pay_or_rec = "receive"
currency = "USD"
notional = 1e6
spread = 1e-3
basis_swap_conv = "USD-SOFR-CME-OIS"
reference_swap_conv = "USD-SOFR-OIS"
business_day_convention = "F"
holiday_convention = "USGS"
prod_swap_spread_basis_swap = qfCreateProductSwapSpreadBasisSwap(
    effective_date,
    term_or_termination_date,
    pay_or_rec,
    currency,
    notional,
    spread,
    basis_swap_conv,
    reference_swap_conv,
    business_day_convention,
    holiday_convention)
display(qfDisplayProduct(prod_swap_spread_basis_swap))
print("Product (de-)serialization:")
### serialization
path = 'prod_overnight_index_future.pickle'
qfWriteProductToFile(prod_swap_spread_basis_swap, path)
# deserialize
prod_swap_spread_basis_swap_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_swap_spread_basis_swap_retrieved))
# house keeping
os.remove(path)
### from data convention
print("Product From Data Convention:")
axis1 = "5Y"
values = 0.05
data_conv = "USD-SOFR-OIS-OVER-USD-SOFR-CME-OIS-BASIS-SWAP"
prod_swap_spread_basis_swap_from_conv = qfCreateProductFromDataConvention(
    value_date,
    data_conv,
    axis1,
    values
)
display(qfDisplayProduct(prod_swap_spread_basis_swap_from_conv))
path = 'prod_swap_spread_basis_swap_from_conv.pickle'
qfWriteProductToFile(prod_swap_spread_basis_swap_from_conv, path)
# deserialize
prod_swap_spread_basis_swap_from_conv_retrieved = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_swap_spread_basis_swap_from_conv_retrieved))
# house keeping
os.remove(path)

Product creation and display:

                         Name                           Value
0                Product Type  PRODUCT_SWAP_SPREAD_BASIS_SWAP
1                    Notional                       1000000.0
2                    Currency                             USD
3               Long Or Short                            LONG
4              Effective Date                      2026-03-23
5    Term Or Termination Date                              1Y
6                  Pay Or Rec                         RECEIVE
7                    Currency                             USD
8                    Notional                       1000000.0
9                      Spread                           0.001
10      Basis Swap Convention                USD-SOFR-CME-OIS
11  Reference Swap Convention                    USD-SOFR-OIS
12    Business Day Convention                               F
13         Holiday Convention                            USGS

Product (de-)serialization:

                         Name                           Value
0                Product Type  PRODUCT_SWAP_SPREAD_BASIS_SWAP
1                    Notional                       1000000.0
2                    Currency                             USD
3               Long Or Short                            LONG
4              Effective Date                      2026-03-23
5    Term Or Termination Date                              1Y
6                  Pay Or Rec                         RECEIVE
7                    Currency                             USD
8                    Notional                       1000000.0
9                      Spread                           0.001
10      Basis Swap Convention                USD-SOFR-CME-OIS
11  Reference Swap Convention                    USD-SOFR-OIS
12    Business Day Convention                               F
13         Holiday Convention                            USGS

Product From Data Convention:

                         Name                           Value
0                Product Type  PRODUCT_SWAP_SPREAD_BASIS_SWAP
1                    Notional                      10000000.0
2                    Currency                             USD
3               Long Or Short                            LONG
4              Effective Date                      2026-03-30
5    Term Or Termination Date                              5Y
6                  Pay Or Rec                         RECEIVE
7                    Currency                             USD
8                    Notional                      10000000.0
9                      Spread                            0.05
10      Basis Swap Convention                USD-SOFR-CME-OIS
11  Reference Swap Convention                    USD-SOFR-OIS
12    Business Day Convention                               P
13         Holiday Convention                             NYC

                         Name                           Value
0                Product Type  PRODUCT_SWAP_SPREAD_BASIS_SWAP
1                    Notional                      10000000.0
2                    Currency                             USD
3               Long Or Short                            LONG
4              Effective Date                      2026-03-30
5    Term Or Termination Date                              5Y
6                  Pay Or Rec                         RECEIVE
7                    Currency                             USD
8                    Notional                      10000000.0
9                      Spread                            0.05
10      Basis Swap Convention                USD-SOFR-CME-OIS
11  Reference Swap Convention                    USD-SOFR-OIS
12    Business Day Convention                               P
13         Holiday Convention                             NYC