In [1]:
import sys, os
import numpy as np
repo_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
if repo_root not in sys.path:
    sys.path.insert(0, repo_root)
print("Added to sys.path:", repo_root)
from fixedincomelib import *
print("Fixed Income Library is loaded.")

Added to sys.path: /Users/tiffanyyan/Documents/GitHub/QuantBricker
Fixed Income Library is loaded.

## Product Bullet Cashflow

In [3]:
# parametric product
termination_date = '2026-05-26'
currency = 'USD'
notional = 1e6
long_or_short = 'LONG'
payment_date = qfAddPeriod(termination_date, '2D', 'F', 'USGS')
prod_bullet_cashflow_1 = qfCreateProductBulletCashflow(
    termination_date,
    currency,
    notional,
    long_or_short
)
prod_bullet_cashflow_2 = qfCreateProductBulletCashflow(
    termination_date,
    currency,
    notional,
    long_or_short,
    payment_date
)

In [4]:
# displayer
display(qfDisplayProduct(prod_bullet_cashflow_1))
display(qfDisplayProduct(prod_bullet_cashflow_2))

               Name                    Value
0      Product Type  PRODUCT_BULLET_CASHFLOW
1          Notional                1000000.0
2          Currency                      USD
3     Long Or Short                     LONG
4  Termination Date               2026-05-26
5      Payment Date               2026-05-26

               Name                    Value
0      Product Type  PRODUCT_BULLET_CASHFLOW
1          Notional                1000000.0
2          Currency                      USD
3     Long Or Short                     LONG
4  Termination Date               2026-05-28
5      Payment Date               2026-05-28

In [5]:
# serialization
# serialize
path = 'product_bullet_cashflow.pickle'
qfWriteProductToFile(prod_bullet_cashflow_1, path)
# deserialize
prod_bullet_cashflow_1_back = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_bullet_cashflow_1_back))
# house keeping
os.remove(path)

               Name                    Value
0      Product Type  PRODUCT_BULLET_CASHFLOW
1          Notional                1000000.0
2          Currency                      USD
3     Long Or Short                     LONG
4  Termination Date               2026-05-26
5      Payment Date               2026-05-26

## Product Fixed Accrued

In [6]:
# parametric product
effecitve_date = '2026-03-26'
termination_date = '2026-05-26'
currency = 'USD'
notional = 1e6
accrual_basis = 'ACT/360'
business_day_convention = 'F'
holiday_convention = 'USGS'
pay_offset = '2D'
payment_date = qfAddPeriod(termination_date, pay_offset, business_day_convention, holiday_convention)
prod_fixed_accrued_1 = qfCreateProducFixedAccrued(
    effecitve_date,
    termination_date,
    currency,
    notional,
    accrual_basis
)
prod_fixed_accrued_2 = qfCreateProducFixedAccrued(
    effecitve_date,
    termination_date,
    currency,
    notional,
    accrual_basis,
    payment_date,
    business_day_convention, 
    holiday_convention
)

In [7]:
# displayer
display(qfDisplayProduct(prod_fixed_accrued_1))
display(qfDisplayProduct(prod_fixed_accrued_2))

                      Name                  Value
0             Product Type  PRODUCT_FIXED_ACCRUED
1                 Notional              1000000.0
2                 Currency                    USD
3            Long Or Short                   LONG
4           Effective Date             2026-03-26
5         Termination Date             2026-05-26
6            Accrual Basis                ACT/360
7             Payment Date             2026-05-26
8  Business Day Convention                      F
9       Holiday Convention                   USGS

                      Name                  Value
0             Product Type  PRODUCT_FIXED_ACCRUED
1                 Notional              1000000.0
2                 Currency                    USD
3            Long Or Short                   LONG
4           Effective Date             2026-03-26
5         Termination Date             2026-05-26
6            Accrual Basis                ACT/360
7             Payment Date             2026-05-28
8  Business Day Convention                      F
9       Holiday Convention                   USGS

In [8]:
# serialization
# serialize
path = 'product_fixed_accrued.pickle'
qfWriteProductToFile(prod_fixed_accrued_2, path)
# deserialize
prod_fixed_accrued_2_back = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_fixed_accrued_2_back))
# house keeping
os.remove(path)

                      Name                  Value
0             Product Type  PRODUCT_FIXED_ACCRUED
1                 Notional              1000000.0
2                 Currency                    USD
3            Long Or Short                   LONG
4           Effective Date             2026-03-26
5         Termination Date             2026-05-26
6            Accrual Basis                ACT/360
7             Payment Date             2026-05-28
8  Business Day Convention                      F
9       Holiday Convention                   USGS

## Product Overnight Index Cashflow

In [9]:
# parametric product
effecitve_date = '2026-03-26'
termination_date = '2027-03-26'
term = '1Y'
overnight_index = 'SOFR-1B'
notional = 1e6
compounding_method = 'compound'
spread = 0.005
business_day_convention = 'F'
holiday_convention = 'USGS'
pay_offset = '2D'
payment_date = qfAddPeriod(termination_date, pay_offset, business_day_convention, holiday_convention)
product_on_cashflow_1 = qfCreateProductOvernightIndexCashflow(
    effecitve_date,
    termination_date,
    overnight_index,
    notional)
product_on_cashflow_2 = qfCreateProductOvernightIndexCashflow(
    effecitve_date,
    term,
    overnight_index,
    notional,
    compounding_method,
    spread,
    payment_date)

In [10]:
# displayer
display(qfDisplayProduct(product_on_cashflow_1))
display(qfDisplayProduct(product_on_cashflow_2))

                 Name                             Value
0        Product Type  PRODUCT_OVERNIGHT_INDEX_CASHFLOW
1            Notional                         1000000.0
2            Currency                               USD
3       Long Or Short                              LONG
4      Effective Date                        2026-03-26
5    Termination Date                        2027-03-26
6            ON Index                 SOFRON Actual/360
7  Compounding Method                          COMPOUND
8              Spread                               0.0
9        Payment Date                        2027-03-26

                 Name                             Value
0        Product Type  PRODUCT_OVERNIGHT_INDEX_CASHFLOW
1            Notional                         1000000.0
2            Currency                               USD
3       Long Or Short                              LONG
4      Effective Date                        2026-03-26
5    Termination Date                        2027-03-29
6            ON Index                 SOFRON Actual/360
7  Compounding Method                          COMPOUND
8              Spread                             0.005
9        Payment Date                        2027-03-30

In [11]:
# serialization
# serialize
path = 'product_on_cashflow.pickle'
qfWriteProductToFile(product_on_cashflow_2, path)
# deserialize
product_on_cashflow_2_back = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(product_on_cashflow_2_back))
# house keeping
os.remove(path)

                 Name                             Value
0        Product Type  PRODUCT_OVERNIGHT_INDEX_CASHFLOW
1            Notional                         1000000.0
2            Currency                               USD
3       Long Or Short                              LONG
4      Effective Date                        2026-03-26
5    Termination Date                        2027-03-29
6            ON Index                 SOFRON Actual/360
7  Compounding Method                          COMPOUND
8              Spread                             0.005
9        Payment Date                        2027-03-30

## Product Overnight Index Future

In [12]:
# parametric product
effective_date = '2026-03-26'
termination_date = '2026-06-26'
on_index = 'SOFR-1B'
pay_or_rec = 'pay'
amount = 1e4
accrual_basis = 'ACT/360'
accrual_period = '3M'
prod_oi_future_1 = qfCreateProductOvernightIndexFuture(
    effective_date,
    termination_date,
    on_index,
    pay_or_rec,
    amount,
    accrual_basis,
    accrual_period,
)
prod_oi_future_2 = qfCreateProductOvernightIndexFuture(
    effective_date,
    termination_date,
    on_index,
    pay_or_rec,
    amount,
    accrual_basis,
    accrual_period,
    pay_business_day_convention='MF',
    pay_holiday_convention='NYC',
    contractual_notional=1e6,
    basis_point=25.0,
    strike=0.005,
    rate_cut_off_days_offset='1D',
    payment_offset='2D',
)

In [13]:
# displayer
display(qfDisplayProduct(prod_oi_future_1))
display(qfDisplayProduct(prod_oi_future_2))

                               Name                           Value
0                      Product Type  PRODUCT_OVERNIGHT_INDEX_FUTURE
1                          Notional                  250000000000.0
2                          Currency                             USD
3                     Long Or Short                            LONG
4                    Effective Date                      2026-03-26
5                  Termination Date                      2026-06-26
6                          ON Index               SOFRON Actual/360
7                    Pay Or Receive                             PAY
8                            Amount                         10000.0
9              Contractual Notional                       1000000.0
10                      Basis Point                            25.0
11                           Strike                             0.0
12                    Accrual Basis                         ACT/360
13                   Accrual Period                              3M
14  Payment Business Day Convention                               F
15       Payment Holiday Convention                            USGS
16         Rate Cut Off Days Offset                              0D
17                   Payment Offset                              0D

                               Name                           Value
0                      Product Type  PRODUCT_OVERNIGHT_INDEX_FUTURE
1                          Notional                  250000000000.0
2                          Currency                             USD
3                     Long Or Short                            LONG
4                    Effective Date                      2026-03-26
5                  Termination Date                      2026-06-26
6                          ON Index               SOFRON Actual/360
7                    Pay Or Receive                             PAY
8                            Amount                         10000.0
9              Contractual Notional                       1000000.0
10                      Basis Point                            25.0
11                           Strike                           0.005
12                    Accrual Basis                         ACT/360
13                   Accrual Period                              3M
14  Payment Business Day Convention                              MF
15       Payment Holiday Convention                             NYC
16         Rate Cut Off Days Offset                              1D
17                   Payment Offset                              2D

In [14]:
# serialization
path = 'product_oi_future.pickle'
qfWriteProductToFile(prod_oi_future_2, path)
prod_oi_future_2_back = qfReadProductFromFile(path)
display(qfDisplayProduct(prod_oi_future_2_back))
os.remove(path)

                               Name                           Value
0                      Product Type  PRODUCT_OVERNIGHT_INDEX_FUTURE
1                          Notional                  250000000000.0
2                          Currency                             USD
3                     Long Or Short                            LONG
4                    Effective Date                      2026-03-26
5                  Termination Date                      2026-06-26
6                          ON Index               SOFRON Actual/360
7                    Pay Or Receive                             PAY
8                            Amount                         10000.0
9              Contractual Notional                       1000000.0
10                      Basis Point                            25.0
11                           Strike                           0.005
12                    Accrual Basis                         ACT/360
13                   Accrual Period                              3M
14  Payment Business Day Convention                              MF
15       Payment Holiday Convention                             NYC
16         Rate Cut Off Days Offset                              1D
17                   Payment Offset                              2D

In [15]:
# product factory
value_date = '2025-09-25'
data_convention = 'SOFR-FUTURE-3M'
axis1 = '2025-09-25x2025-12-25'
values = 0.0
prod_oi_future_from_convention = qfCreateProductFromDataConvention(
    value_date,
    data_convention,
    axis1,
    values,
)
qfDisplayProduct(prod_oi_future_from_convention)

                               Name                           Value
0                      Product Type  PRODUCT_OVERNIGHT_INDEX_FUTURE
1                          Notional                      25000000.0
2                          Currency                             USD
3                     Long Or Short                            LONG
4                    Effective Date                      2025-09-25
5                  Termination Date                      2025-12-25
6                          ON Index               SOFRON Actual/360
7                    Pay Or Receive                             PAY
8                            Amount                             1.0
9              Contractual Notional                       1000000.0
10                      Basis Point                            25.0
11                           Strike                             0.0
12                    Accrual Basis                         ACT/360
13                   Accrual Period                              3M
14  Payment Business Day Convention                              MF
15       Payment Holiday Convention                            USGS
16         Rate Cut Off Days Offset                              0D
17                   Payment Offset                              2D

## Product Overnight Index Swap (OIS)

In [16]:
# parametric product
effective_date = '2025-05-25'
termination_date = '2027-05-25'
term = '2Y'
pay_offset = '2D'
on_index = 'SOFR-1B'
fixed_rate = 0.04
pay_or_rec = 'pay'
notional = 1e6
accrual_period = '1Y'
accrual_basis = 'ACT/360'
floating_leg_accrual_period = '1Y'
business_day_convention = 'F'
holiday_convention = 'USGS'
spread = 0.005
compounding_method = 'compound'
prod_oi_swap_1 = qfCreateProductOvernightIndexSwap(
    effective_date,
    termination_date,
    pay_offset,
    on_index,
    fixed_rate,
    pay_or_rec,
    notional,
    accrual_period,
    accrual_basis,
)
prod_oi_swap_2 = qfCreateProductOvernightIndexSwap(
    effective_date,
    term,
    pay_offset,
    on_index,
    fixed_rate,
    pay_or_rec,
    notional,
    accrual_period,
    accrual_basis,
    floating_leg_accrual_period,
    business_day_convention,
    holiday_convention,
    spread,
    rate_cutoff_days_offset='1D',
    compounding_method=compounding_method,
)

In [17]:
# displayer
display(qfDisplayProduct(prod_oi_swap_1))
display(qfDisplayProduct(prod_oi_swap_2))

                           Name                         Value
0                  Product Type  PRODUCT_OVERNIGHT_INDEX_SWAP
1                      Notional                     1000000.0
2                      Currency                           USD
3                 Long Or Short                          LONG
4                Effective Date                    2025-05-25
5              Termination Date                    2027-05-25
6                Payment Offset                            2D
7                      ON Index             SOFRON Actual/360
8                    Fixed Rate                          0.04
9                Pay Or Receive                           PAY
10               Accrual Period                            1Y
11                Accrual Basis                       ACT/360
12  Floating Leg Accrual Period                            1Y
13      Business Day Convention                             F
14           Holiday Convention                          USGS
15           Compounding Method                      compound

                           Name                         Value
0                  Product Type  PRODUCT_OVERNIGHT_INDEX_SWAP
1                      Notional                     1000000.0
2                      Currency                           USD
3                 Long Or Short                          LONG
4                Effective Date                    2025-05-25
5              Termination Date                    2027-05-25
6                Payment Offset                            2D
7                      ON Index             SOFRON Actual/360
8                    Fixed Rate                          0.04
9                Pay Or Receive                           PAY
10               Accrual Period                            1Y
11                Accrual Basis                       ACT/360
12  Floating Leg Accrual Period                            1Y
13      Business Day Convention                             F
14           Holiday Convention                          USGS
15           Compounding Method                      compound

In [18]:
# examine important member functions
idx = 0
display(qfDisplayProduct(prod_oi_swap_2.floating_leg_cash_flow(idx)))
display(qfDisplayProduct(prod_oi_swap_2.fixed_leg_cash_flow(idx)))

                 Name                             Value
0        Product Type  PRODUCT_OVERNIGHT_INDEX_CASHFLOW
1            Notional                         1000000.0
2            Currency                               USD
3       Long Or Short                              LONG
4      Effective Date                        2025-05-27
5    Termination Date                        2026-05-26
6            ON Index                 SOFRON Actual/360
7  Compounding Method                          COMPOUND
8              Spread                             0.005
9        Payment Date                        2026-05-28

                      Name                  Value
0             Product Type  PRODUCT_FIXED_ACCRUED
1                 Notional              1000000.0
2                 Currency                    USD
3            Long Or Short                   LONG
4           Effective Date             2025-05-27
5         Termination Date             2026-05-26
6            Accrual Basis                ACT/360
7             Payment Date             2026-05-28
8  Business Day Convention                      F
9       Holiday Convention                   USGS

In [19]:
# serialization
path = 'product_oi_swap.pickle'
qfWriteProductToFile(prod_oi_swap_2, path)
prod_oi_swap_2_back = qfReadProductFromFile(path)
display(qfDisplayProduct(prod_oi_swap_2_back))
os.remove(path)

                           Name                         Value
0                  Product Type  PRODUCT_OVERNIGHT_INDEX_SWAP
1                      Notional                     1000000.0
2                      Currency                           USD
3                 Long Or Short                          LONG
4                Effective Date                    2025-05-25
5              Termination Date                    2027-05-25
6                Payment Offset                            2D
7                      ON Index             SOFRON Actual/360
8                    Fixed Rate                          0.04
9                Pay Or Receive                           PAY
10               Accrual Period                            1Y
11                Accrual Basis                       ACT/360
12  Floating Leg Accrual Period                            1Y
13      Business Day Convention                             F
14           Holiday Convention                          USGS
15           Compounding Method                      compound

In [20]:
# product factory
value_date = '2025-09-25'
data_convention = 'USD-SOFR-OIS'
axis1 = '5Y'
values = 0.03
prod_oi_swap_from_convention = qfCreateProductFromDataConvention(
    value_date,
    data_convention,
    axis1,
    values,
)
display(qfDisplayProduct(prod_oi_swap_from_convention))

# notional override via kwargs (previously silently ignored due to a "notinoal" typo in
# ProductFactory.create_overnight_index_swap; now fixed)
prod_oi_swap_from_convention_notional = qfCreateProductFromDataConvention(
    value_date,
    data_convention,
    axis1,
    values,
    notional=5e6,
)
assert prod_oi_swap_from_convention_notional.notional == 5e6
display(qfDisplayProduct(prod_oi_swap_from_convention_notional))

                           Name                         Value
0                  Product Type  PRODUCT_OVERNIGHT_INDEX_SWAP
1                      Notional                       10000.0
2                      Currency                           USD
3                 Long Or Short                          LONG
4                Effective Date                    2025-09-25
5              Termination Date                    2030-09-25
6                Payment Offset                            2D
7                      ON Index             SOFRON Actual/360
8                    Fixed Rate                          0.03
9                Pay Or Receive                       RECEIVE
10               Accrual Period                            1Y
11                Accrual Basis                       ACT/360
12  Floating Leg Accrual Period                            1Y
13      Business Day Convention                            MF
14           Holiday Convention                           NYC
15           Compounding Method                      compound

                           Name                         Value
0                  Product Type  PRODUCT_OVERNIGHT_INDEX_SWAP
1                      Notional                     5000000.0
2                      Currency                           USD
3                 Long Or Short                          LONG
4                Effective Date                    2025-09-25
5              Termination Date                    2030-09-25
6                Payment Offset                            2D
7                      ON Index             SOFRON Actual/360
8                    Fixed Rate                          0.03
9                Pay Or Receive                       RECEIVE
10               Accrual Period                            1Y
11                Accrual Basis                       ACT/360
12  Floating Leg Accrual Period                            1Y
13      Business Day Convention                            MF
14           Holiday Convention                           NYC
15           Compounding Method                      compound

## Product Overnight Index Basis Swap (OI vs OI)

In [21]:
# parametric product (leg 1 and leg 2 both genuine overnight indices)
effective_date = '2025-05-25'
termination_date = '2027-05-25'
term = '2Y'
payment_offset = '2D'
notional = 1e6
on_index_leg_1 = 'SOFR-1B'
on_index_leg_2 = 'FF-1B'
spread_over_leg_1 = 0.001
pay_or_rec_leg_1 = 'pay'
accrual_period_1 = '3M'
accrual_period_2 = '3M'
accrual_basis = 'ACT/360'
rate_cut_off_days_offset = '0D'
prod_oi_basis_swap_1 = qfCreateProductOvernightIndexBasisSwap(
    effective_date,
    termination_date,
    payment_offset,
    notional,
    on_index_leg_1,
    on_index_leg_2,
    spread_over_leg_1,
    pay_or_rec_leg_1,
    accrual_period_1,
    accrual_period_2,
    accrual_basis,
    rate_cut_off_days_offset,
)
prod_oi_basis_swap_2 = qfCreateProductOvernightIndexBasisSwap(
    effective_date,
    term,
    payment_offset,
    notional,
    on_index_leg_1,
    on_index_leg_2,
    spread_over_leg_1,
    pay_or_rec_leg_1,
    accrual_period_1,
    accrual_period_2,
    accrual_basis,
    rate_cut_off_days_offset,
    pay_business_day_convention='MF',
    pay_holiday_convention='NYC',
    compounding_method='compound',
)

In [22]:
# displayer
display(qfDisplayProduct(prod_oi_basis_swap_1))
display(qfDisplayProduct(prod_oi_basis_swap_2))

                       Name                               Value
0              Product Type  PRODUCT_OVERNIGHT_INDEX_BASIS_SWAP
1                  Notional                           1000000.0
2                  Currency                                 USD
3             Long Or Short                                LONG
4            Effective Date                          2025-05-25
5          Termination Date                          2027-05-25
6            Payment Offset                                  2D
7                ON Index 1                   SOFRON Actual/360
8                ON Index 2               FedFundsON Actual/360
9         Spread Over Leg 1                               0.001
10     Pay Or Receive Leg 1                                 PAY
11     Accrual Period Leg 1                                  3M
12     Accrual Period Leg 2                                  3M
13            Accrual Basis                             ACT/360
14  Business Day Convention                                   F
15       Holiday Convention                                USGS
16       Compounding Method                            compound

                       Name                               Value
0              Product Type  PRODUCT_OVERNIGHT_INDEX_BASIS_SWAP
1                  Notional                           1000000.0
2                  Currency                                 USD
3             Long Or Short                                LONG
4            Effective Date                          2025-05-25
5          Termination Date                          2027-05-25
6            Payment Offset                                  2D
7                ON Index 1                   SOFRON Actual/360
8                ON Index 2               FedFundsON Actual/360
9         Spread Over Leg 1                               0.001
10     Pay Or Receive Leg 1                                 PAY
11     Accrual Period Leg 1                                  3M
12     Accrual Period Leg 2                                  3M
13            Accrual Basis                             ACT/360
14  Business Day Convention                                  MF
15       Holiday Convention                                 NYC
16       Compounding Method                            compound

In [23]:
# examine important member functions
idx = 0
display(qfDisplayProduct(prod_oi_basis_swap_2.floating_leg_1_cash_flow(idx)))
display(qfDisplayProduct(prod_oi_basis_swap_2.floating_leg_2_cash_flow(idx)))

                 Name                             Value
0        Product Type  PRODUCT_OVERNIGHT_INDEX_CASHFLOW
1            Notional                         1000000.0
2            Currency                               USD
3       Long Or Short                              LONG
4      Effective Date                        2025-05-27
5    Termination Date                        2025-08-25
6            ON Index                 SOFRON Actual/360
7  Compounding Method                          COMPOUND
8              Spread                             0.001
9        Payment Date                        2025-08-27

                 Name                             Value
0        Product Type  PRODUCT_OVERNIGHT_INDEX_CASHFLOW
1            Notional                         1000000.0
2            Currency                               USD
3       Long Or Short                              LONG
4      Effective Date                        2025-05-27
5    Termination Date                        2025-08-25
6            ON Index             FedFundsON Actual/360
7  Compounding Method                          COMPOUND
8              Spread                               0.0
9        Payment Date                        2025-08-27

In [24]:
# serialization
path = 'product_oi_basis_swap.pickle'
qfWriteProductToFile(prod_oi_basis_swap_2, path)
prod_oi_basis_swap_2_back = qfReadProductFromFile(path)
display(qfDisplayProduct(prod_oi_basis_swap_2_back))
os.remove(path)

                       Name                               Value
0              Product Type  PRODUCT_OVERNIGHT_INDEX_BASIS_SWAP
1                  Notional                           1000000.0
2                  Currency                                 USD
3             Long Or Short                                LONG
4            Effective Date                          2025-05-25
5          Termination Date                          2027-05-25
6            Payment Offset                                  2D
7                ON Index 1                   SOFRON Actual/360
8                ON Index 2               FedFundsON Actual/360
9         Spread Over Leg 1                               0.001
10     Pay Or Receive Leg 1                                 PAY
11     Accrual Period Leg 1                                  3M
12     Accrual Period Leg 2                                  3M
13            Accrual Basis                             ACT/360
14  Business Day Convention                                  MF
15       Holiday Convention                                 NYC
16       Compounding Method                            compound

### OI vs IBOR leg (USD-TERM-SOFR-3M)

In [25]:
# parametric product - leg 2 is now a genuine IBOR index (USD-TERM-SOFR-3M).
# ProductOvernightIndexCashflow auto-detects the IborIndex wrapper (vs a true
# ql overnight index) via IndexRegistry().get(...) and adapts accordingly.
prod_oi_basis_swap_ibor = qfCreateProductOvernightIndexBasisSwap(
    effective_date,
    term,
    payment_offset,
    notional,
    on_index_leg_1,
    'USD-TERM-SOFR-3M',
    spread_over_leg_1,
    pay_or_rec_leg_1,
    accrual_period_1,
    accrual_period_2,
    accrual_basis,
    rate_cut_off_days_offset,
)
display(qfDisplayProduct(prod_oi_basis_swap_ibor))
display(qfDisplayProduct(prod_oi_basis_swap_ibor.floating_leg_1_cash_flow(0)))
display(qfDisplayProduct(prod_oi_basis_swap_ibor.floating_leg_2_cash_flow(0)))

                       Name                               Value
0              Product Type  PRODUCT_OVERNIGHT_INDEX_BASIS_SWAP
1                  Notional                           1000000.0
2                  Currency                                 USD
3             Long Or Short                                LONG
4            Effective Date                          2025-05-25
5          Termination Date                          2027-05-25
6            Payment Offset                                  2D
7                ON Index 1                   SOFRON Actual/360
8                ON Index 2                    USD-TERM-SOFR-3M
9         Spread Over Leg 1                               0.001
10     Pay Or Receive Leg 1                                 PAY
11     Accrual Period Leg 1                                  3M
12     Accrual Period Leg 2                                  3M
13            Accrual Basis                             ACT/360
14  Business Day Convention                                   F
15       Holiday Convention                                USGS
16       Compounding Method                            compound

                 Name                             Value
0        Product Type  PRODUCT_OVERNIGHT_INDEX_CASHFLOW
1            Notional                         1000000.0
2            Currency                               USD
3       Long Or Short                              LONG
4      Effective Date                        2025-05-27
5    Termination Date                        2025-08-25
6            ON Index                 SOFRON Actual/360
7  Compounding Method                          COMPOUND
8              Spread                             0.001
9        Payment Date                        2025-08-27

                 Name                             Value
0        Product Type  PRODUCT_OVERNIGHT_INDEX_CASHFLOW
1            Notional                         1000000.0
2            Currency                               USD
3       Long Or Short                              LONG
4      Effective Date                        2025-05-27
5    Termination Date                        2025-08-25
6            ON Index                  USD-TERM-SOFR-3M
7  Compounding Method                          COMPOUND
8              Spread                               0.0
9        Payment Date                        2025-08-27

In [26]:
# product factory
value_date = '2025-09-25'
data_convention = 'USD-SOFR-COMPOUND-OVER-USD-TERM-SOFR-3M-BASIS-SWAP'
axis1 = '5Y'
values = 0.001
prod_oi_basis_swap_from_convention = qfCreateProductFromDataConvention(
    value_date,
    data_convention,
    axis1,
    values,
)
display(qfDisplayProduct(prod_oi_basis_swap_from_convention))
display(qfDisplayProduct(prod_oi_basis_swap_from_convention.floating_leg_2_cash_flow(0)))

                       Name                               Value
0              Product Type  PRODUCT_OVERNIGHT_INDEX_BASIS_SWAP
1                  Notional                             10000.0
2                  Currency                                 USD
3             Long Or Short                                LONG
4            Effective Date                          2025-09-25
5          Termination Date                          2030-09-25
6            Payment Offset                                  2D
7                ON Index 1                   SOFRON Actual/360
8                ON Index 2                    USD-TERM-SOFR-3M
9         Spread Over Leg 1                               0.001
10     Pay Or Receive Leg 1                             RECEIVE
11     Accrual Period Leg 1                                  3M
12     Accrual Period Leg 2                                  3M
13            Accrual Basis                             ACT/360
14  Business Day Convention                                  MF
15       Holiday Convention                                 NYC
16       Compounding Method                            compound

                 Name                             Value
0        Product Type  PRODUCT_OVERNIGHT_INDEX_CASHFLOW
1            Notional                           10000.0
2            Currency                               USD
3       Long Or Short                              LONG
4      Effective Date                        2025-09-25
5    Termination Date                        2025-12-26
6            ON Index                  USD-TERM-SOFR-3M
7  Compounding Method                          COMPOUND
8              Spread                               0.0
9        Payment Date                        2025-12-30

## Product OIS Basis Swap (new) (OI vs OI)

In [27]:
# parametric product
effective_date = '2025-05-25'
termination_date = '2027-05-25'
term = '2Y'
payment_offset = '2D'
notional = 1e6
on_index_leg_1 = 'FF-1B'
on_index_leg_2 = 'SOFR-1B'
spread_over_leg_1 = 0.001
pay_or_rec_leg_1 = 'pay'
accrual_period_1 = '3M'
accrual_period_2 = '3M'
accrual_basis = 'ACT/360'
rate_cut_off_days_offset = '0D'
prod_ois_basis_swap_1 = qfCreateProductOISBasisSwap(
    effective_date,
    termination_date,
    payment_offset,
    notional,
    on_index_leg_1,
    on_index_leg_2,
    spread_over_leg_1,
    pay_or_rec_leg_1,
    accrual_period_1,
    accrual_period_2,
    accrual_basis,
    rate_cut_off_days_offset,
)
prod_ois_basis_swap_2 = qfCreateProductOISBasisSwap(
    effective_date,
    term,
    payment_offset,
    notional,
    on_index_leg_1,
    on_index_leg_2,
    spread_over_leg_1,
    pay_or_rec_leg_1,
    accrual_period_1,
    accrual_period_2,
    accrual_basis,
    rate_cut_off_days_offset,
    pay_business_day_convention='MF',
    pay_holiday_convention='NYC',
    compounding_method='compound',
)

In [28]:
# displayer
display(qfDisplayProduct(prod_ois_basis_swap_1))
display(qfDisplayProduct(prod_ois_basis_swap_2))

                       Name                   Value
0              Product Type  PRODUCT_OIS_BASIS_SWAP
1                  Notional               1000000.0
2                  Currency                     USD
3             Long Or Short                    LONG
4            Effective Date              2025-05-25
5          Termination Date              2027-05-25
6            Payment Offset                      2D
7                ON Index 1   FedFundsON Actual/360
8                ON Index 2       SOFRON Actual/360
9         Spread Over Leg 1                   0.001
10     Pay Or Receive Leg 1                     PAY
11     Accrual Period Leg 1                      3M
12     Accrual Period Leg 2                      3M
13            Accrual Basis                 ACT/360
14  Business Day Convention                       F
15       Holiday Convention                    USGS
16       Compounding Method                compound

                       Name                   Value
0              Product Type  PRODUCT_OIS_BASIS_SWAP
1                  Notional               1000000.0
2                  Currency                     USD
3             Long Or Short                    LONG
4            Effective Date              2025-05-25
5          Termination Date              2027-05-25
6            Payment Offset                      2D
7                ON Index 1   FedFundsON Actual/360
8                ON Index 2       SOFRON Actual/360
9         Spread Over Leg 1                   0.001
10     Pay Or Receive Leg 1                     PAY
11     Accrual Period Leg 1                      3M
12     Accrual Period Leg 2                      3M
13            Accrual Basis                 ACT/360
14  Business Day Convention                      MF
15       Holiday Convention                     NYC
16       Compounding Method                compound

In [29]:
# examine important member functions
idx = 0
display(qfDisplayProduct(prod_ois_basis_swap_2.floating_leg_1_cash_flow(idx)))
display(qfDisplayProduct(prod_ois_basis_swap_2.floating_leg_2_cash_flow(idx)))

                 Name                             Value
0        Product Type  PRODUCT_OVERNIGHT_INDEX_CASHFLOW
1            Notional                         1000000.0
2            Currency                               USD
3       Long Or Short                              LONG
4      Effective Date                        2025-05-27
5    Termination Date                        2025-08-25
6            ON Index             FedFundsON Actual/360
7  Compounding Method                          COMPOUND
8              Spread                             0.001
9        Payment Date                        2025-08-27

                 Name                             Value
0        Product Type  PRODUCT_OVERNIGHT_INDEX_CASHFLOW
1            Notional                         1000000.0
2            Currency                               USD
3       Long Or Short                              LONG
4      Effective Date                        2025-05-27
5    Termination Date                        2025-08-25
6            ON Index                 SOFRON Actual/360
7  Compounding Method                          COMPOUND
8              Spread                               0.0
9        Payment Date                        2025-08-27

In [30]:
# serialization
path = 'product_ois_basis_swap.pickle'
qfWriteProductToFile(prod_ois_basis_swap_2, path)
prod_ois_basis_swap_2_back = qfReadProductFromFile(path)
display(qfDisplayProduct(prod_ois_basis_swap_2_back))
os.remove(path)

                       Name                   Value
0              Product Type  PRODUCT_OIS_BASIS_SWAP
1                  Notional               1000000.0
2                  Currency                     USD
3             Long Or Short                    LONG
4            Effective Date              2025-05-25
5          Termination Date              2027-05-25
6            Payment Offset                      2D
7                ON Index 1   FedFundsON Actual/360
8                ON Index 2       SOFRON Actual/360
9         Spread Over Leg 1                   0.001
10     Pay Or Receive Leg 1                     PAY
11     Accrual Period Leg 1                      3M
12     Accrual Period Leg 2                      3M
13            Accrual Basis                 ACT/360
14  Business Day Convention                      MF
15       Holiday Convention                     NYC
16       Compounding Method                compound

In [31]:
# product factory
value_date = '2025-09-25'
data_convention = 'USD-FF-3M-OVER-USD-SOFR-OIS-3M'
axis1 = '5Y'
values = 0.001
prod_ois_basis_swap_from_convention = qfCreateProductFromDataConvention(
    value_date,
    data_convention,
    axis1,
    values,
)
display(qfDisplayProduct(prod_ois_basis_swap_from_convention))

# notional override via kwargs (previously silently ignored due to a "notinoal" typo in
# ProductFactory.create_ois_basis_swap; now fixed)
prod_ois_basis_swap_from_convention_notional = qfCreateProductFromDataConvention(
    value_date,
    data_convention,
    axis1,
    values,
    notional=2e6,
)
assert prod_ois_basis_swap_from_convention_notional.notional == 2e6
display(qfDisplayProduct(prod_ois_basis_swap_from_convention_notional))

                       Name                   Value
0              Product Type  PRODUCT_OIS_BASIS_SWAP
1                  Notional                 10000.0
2                  Currency                     USD
3             Long Or Short                    LONG
4            Effective Date              2025-09-25
5          Termination Date              2030-09-25
6            Payment Offset                      2D
7                ON Index 1   FedFundsON Actual/360
8                ON Index 2       SOFRON Actual/360
9         Spread Over Leg 1                   0.001
10     Pay Or Receive Leg 1                 RECEIVE
11     Accrual Period Leg 1                      3M
12     Accrual Period Leg 2                      3M
13            Accrual Basis                 ACT/360
14  Business Day Convention                      MF
15       Holiday Convention                     NYC
16       Compounding Method                compound

                       Name                   Value
0              Product Type  PRODUCT_OIS_BASIS_SWAP
1                  Notional               2000000.0
2                  Currency                     USD
3             Long Or Short                    LONG
4            Effective Date              2025-09-25
5          Termination Date              2030-09-25
6            Payment Offset                      2D
7                ON Index 1   FedFundsON Actual/360
8                ON Index 2       SOFRON Actual/360
9         Spread Over Leg 1                   0.001
10     Pay Or Receive Leg 1                 RECEIVE
11     Accrual Period Leg 1                      3M
12     Accrual Period Leg 2                      3M
13            Accrual Basis                 ACT/360
14  Business Day Convention                      MF
15       Holiday Convention                     NYC
16       Compounding Method                compound

## Product Overnight Index Currency Basis Swap (Non-MTM Xccy Basis Swap)

In [32]:
# parametric product
effective_date = '2025-05-25'
termination_date = '2030-05-25'
term = '5Y'
basis_index = 'EONIA-1B'
reference_index = 'SOFR-1B'
pay_or_receive_b = 'pay'
reference_notional = 1e7
fx_spot_r_per_b_0 = 1.08  # USD per EUR
basis_notional = None  # derived from fx_spot
basis_spread = 0.001
basis_on_basis_leg = True
settlement_offset = '2D'
settlement_holidays = 'TARGET'
accrual_period_b = '3M'
accrual_period_r = '3M'
accrual_basis_b = 'ACT/360'
accrual_basis_r = 'ACT/360'
payment_offset_b = '0D'
payment_offset_r = '0D'
prod_xccy_basis_swap_1 = qfCreateProductCrossCurrencyBasisSwapNonMTM(
    effective_date,
    termination_date,
    basis_index,
    reference_index,
    pay_or_receive_b,
    reference_notional,
    fx_spot_r_per_b_0,
    basis_notional,
    basis_spread,
    basis_on_basis_leg,
    settlement_offset,
    settlement_holidays,
    accrual_period_b,
    accrual_period_r,
    accrual_basis_b,
    accrual_basis_r,
    payment_offset_b,
    payment_offset_r,
)
prod_xccy_basis_swap_2 = qfCreateProductCrossCurrencyBasisSwapNonMTM(
    effective_date,
    term,
    basis_index,
    reference_index,
    pay_or_receive_b,
    reference_notional,
    fx_spot_r_per_b_0,
    basis_notional,
    basis_spread,
    basis_on_basis_leg,
    settlement_offset,
    settlement_holidays,
    accrual_period_b,
    accrual_period_r,
    accrual_basis_b,
    accrual_basis_r,
    payment_offset_b,
    payment_offset_r,
    pay_business_day_convention_b='F',
    pay_business_day_convention_r='MF',
    pay_holiday_convention_b='TARGET',
    pay_holiday_convention_r='NYC',
    compounding_method_b='compound',
    compounding_method_r='compound',
    exchange_notional_at_start=True,
    exchange_notional_at_end=True,
)

In [33]:
# displayer
display(qfDisplayProduct(prod_xccy_basis_swap_1))
display(qfDisplayProduct(prod_xccy_basis_swap_2))

                                 Name                            Value
0                        Product Type  PRODUCT_XCCY_BASIS_SWAP_NON_MTM
1                       Long Or Short                             LONG
2                      Effective Date                       2025-05-25
3                    Termination Date                       2030-05-25
4                      Basis Currency                              EUR
5                  Reference Currency                              USD
6                         Basis Index               EoniaON Actual/360
7                     Reference Index                SOFRON Actual/360
8                        Basis Spread                            0.001
9                  Basis On Basis Leg                             True
10                     Pay Or Receive                              PAY
11                     Basis Notional                   9259259.259259
12                 Reference Notional                       10000000.0
13                  FX Spot (R per B)                             1.08
14               Accrual Period Basis                               3M
15           Accrual Period Reference                               3M
16                Accrual Basis Basis                          ACT/360
17            Accrual Basis Reference                          ACT/360
18               Payment Offset Basis                               0D
19           Payment Offset Reference                               0D
20      Business Day Convention Basis                                F
21  Business Day Convention Reference                                F
22           Holiday Convention Basis                           TARGET
23       Holiday Convention Reference                             USGS
24           Compounding Method Basis                         compound
25       Compounding Method Reference                         compound
26         Exchange Notional At Start                             True
27           Exchange Notional At End                             True

                                 Name                            Value
0                        Product Type  PRODUCT_XCCY_BASIS_SWAP_NON_MTM
1                       Long Or Short                             LONG
2                      Effective Date                       2025-05-25
3                    Termination Date                       2030-05-27
4                      Basis Currency                              EUR
5                  Reference Currency                              USD
6                         Basis Index               EoniaON Actual/360
7                     Reference Index                SOFRON Actual/360
8                        Basis Spread                            0.001
9                  Basis On Basis Leg                             True
10                     Pay Or Receive                              PAY
11                     Basis Notional                   9259259.259259
12                 Reference Notional                       10000000.0
13                  FX Spot (R per B)                             1.08
14               Accrual Period Basis                               3M
15           Accrual Period Reference                               3M
16                Accrual Basis Basis                          ACT/360
17            Accrual Basis Reference                          ACT/360
18               Payment Offset Basis                               0D
19           Payment Offset Reference                               0D
20      Business Day Convention Basis                                F
21  Business Day Convention Reference                               MF
22           Holiday Convention Basis                           TARGET
23       Holiday Convention Reference                              NYC
24           Compounding Method Basis                         compound
25       Compounding Method Reference                         compound
26         Exchange Notional At Start                             True
27           Exchange Notional At End                             True

In [34]:
# examine important member functions: legs and notional exchanges
display(qfDisplayProduct(prod_xccy_basis_swap_2.basis_leg.cashflow(0)))
display(qfDisplayProduct(prod_xccy_basis_swap_2.reference_leg.cashflow(0)))
display(qfDisplayProduct(prod_xccy_basis_swap_2.notional_exchange_start_b))
display(qfDisplayProduct(prod_xccy_basis_swap_2.notional_exchange_end_r))

                 Name                             Value
0        Product Type  PRODUCT_OVERNIGHT_INDEX_CASHFLOW
1            Notional                    9259259.259259
2            Currency                               EUR
3       Long Or Short                              LONG
4      Effective Date                        2025-05-26
5    Termination Date                        2025-05-27
6            ON Index                EoniaON Actual/360
7  Compounding Method                          COMPOUND
8              Spread                             0.001
9        Payment Date                        2025-05-27

                 Name                             Value
0        Product Type  PRODUCT_OVERNIGHT_INDEX_CASHFLOW
1            Notional                        10000000.0
2            Currency                               USD
3       Long Or Short                              LONG
4      Effective Date                        2025-05-27
5    Termination Date                        2025-08-27
6            ON Index                 SOFRON Actual/360
7  Compounding Method                          COMPOUND
8              Spread                               0.0
9        Payment Date                        2025-08-27

               Name                    Value
0      Product Type  PRODUCT_BULLET_CASHFLOW
1          Notional           9259259.259259
2          Currency                      EUR
3     Long Or Short                    SHORT
4  Termination Date               2025-05-25
5      Payment Date               2025-05-25

               Name                    Value
0      Product Type  PRODUCT_BULLET_CASHFLOW
1          Notional               10000000.0
2          Currency                      USD
3     Long Or Short                    SHORT
4  Termination Date               2030-05-28
5      Payment Date               2030-05-28

In [35]:
# serialization
path = 'product_xccy_basis_swap.pickle'
qfWriteProductToFile(prod_xccy_basis_swap_2, path)
prod_xccy_basis_swap_2_back = qfReadProductFromFile(path)
display(qfDisplayProduct(prod_xccy_basis_swap_2_back))
os.remove(path)

                                 Name                            Value
0                        Product Type  PRODUCT_XCCY_BASIS_SWAP_NON_MTM
1                       Long Or Short                             LONG
2                      Effective Date                       2025-05-25
3                    Termination Date                       2030-05-27
4                      Basis Currency                              EUR
5                  Reference Currency                              USD
6                         Basis Index               EoniaON Actual/360
7                     Reference Index                SOFRON Actual/360
8                        Basis Spread                            0.001
9                  Basis On Basis Leg                             True
10                     Pay Or Receive                              PAY
11                     Basis Notional                   9259259.259259
12                 Reference Notional                       10000000.0
13                  FX Spot (R per B)                             1.08
14               Accrual Period Basis                               3M
15           Accrual Period Reference                               3M
16                Accrual Basis Basis                          ACT/360
17            Accrual Basis Reference                          ACT/360
18               Payment Offset Basis                               0D
19           Payment Offset Reference                               0D
20      Business Day Convention Basis                                F
21  Business Day Convention Reference                               MF
22           Holiday Convention Basis                           TARGET
23       Holiday Convention Reference                              NYC
24           Compounding Method Basis                         compound
25       Compounding Method Reference                         compound
26         Exchange Notional At Start                             True
27           Exchange Notional At End                             True

In [36]:
# product factory
value_date = '2025-09-25'
data_convention = 'GBP-SONIA-COMPOUND-3M-OVER-USD-SOFR-COMPOUND-3M'
axis1 = '5Y'
values = 0.001
prod_xccy_basis_swap_from_convention = qfCreateProductFromDataConvention(
    value_date,
    data_convention,
    axis1,
    values,
    fx_spot_r_per_b_0=1.25,
    reference_notional=1e7,
)
qfDisplayProduct(prod_xccy_basis_swap_from_convention)

                                 Name                            Value
0                        Product Type  PRODUCT_XCCY_BASIS_SWAP_NON_MTM
1                       Long Or Short                             LONG
2                      Effective Date                       2025-09-25
3                    Termination Date                       2030-09-25
4                      Basis Currency                              GBP
5                  Reference Currency                              USD
6                         Basis Index       SoniaON Actual/365 (Fixed)
7                     Reference Index                SOFRON Actual/360
8                        Basis Spread                            0.001
9                  Basis On Basis Leg                             True
10                     Pay Or Receive                          RECEIVE
11                     Basis Notional                        8000000.0
12                 Reference Notional                       10000000.0
13                  FX Spot (R per B)                             1.25
14               Accrual Period Basis                               3M
15           Accrual Period Reference                               3M
16                Accrual Basis Basis                    ACT/365 FIXED
17            Accrual Basis Reference                          ACT/360
18               Payment Offset Basis                               2D
19           Payment Offset Reference                               2D
20      Business Day Convention Basis                               MF
21  Business Day Convention Reference                               MF
22           Holiday Convention Basis                         USGS,LON
23       Holiday Convention Reference                         USGS,LON
24           Compounding Method Basis                         compound
25       Compounding Method Reference                         compound
26         Exchange Notional At Start                             True
27           Exchange Notional At End                             True

## Product Zero Spread

In [37]:
# parametric product
# NOTE: there is no qf-prefixed factory function for ProductZeroSpread yet,
# so we construct it directly from the class (re-exported via `from fixedincomelib import *`).
termination_date = '2026-05-26'
basis_index = 'SOFR-1B'
reference_index = 'FF-1B'
zero_rate = 0.001
notional = 1e6
long_or_short = 'LONG'
prod_zero_spread_1 = ProductZeroSpread(
    Date(termination_date),
    basis_index,
    reference_index,
    zero_rate,
    notional,
    LongOrShort.from_string(long_or_short),
)

In [38]:
# displayer
display(qfDisplayProduct(prod_zero_spread_1))

               Name                Value
0      Product Type  PRODUCT_ZERO_SPREAD
1          Notional            1000000.0
2          Currency                  USD
3     Long Or Short                 LONG
4  Termination Date           2026-05-26
5             Index    SOFRON Actual/360
6         Zero Rate                0.001

In [39]:
# serialization
path = 'product_zero_spread.pickle'
qfWriteProductToFile(prod_zero_spread_1, path)
prod_zero_spread_1_back = qfReadProductFromFile(path)
display(qfDisplayProduct(prod_zero_spread_1_back))
os.remove(path)

               Name                Value
0      Product Type  PRODUCT_ZERO_SPREAD
1          Notional            1000000.0
2          Currency                  USD
3     Long Or Short                 LONG
4  Termination Date           2026-05-26
5             Index    SOFRON Actual/360
6         Zero Rate                0.001

**Note on `qfCreateProductFromDataConvention` for Zero Spread:** none of the 9 named `ZERO SPREAD` conventions in `data_conventions.json` currently resolve through `IndexRegistry` end-to-end -- 6 reference indices such as `SOFR-1B-CALIB` / `*-FLAT` that were never registered in `indices.json`, and 2 (`SOFR-1B-OVER-USD-ZERO-SPREAD`, `SONIA-1B-OVER-GBP-ZERO-SPREAD`) use a bare currency code (`USD`, `GBP`) as `reference_index`, which `ProductZeroSpread` always tries to resolve as an index. This is a pre-existing data gap, not something this notebook covers; the direct-construction test above remains the coverage for this product type.